### ISSUE TITLE
Debian #751288: Avahi-daemon is noisy

### ISSUE THREAD

**Issue by lathiat** [lathiat/avahi#10]
Package: avahi-daemon
Version: 0.6.31-4

Avahi-daemon fills my logs with

 Jun 11 07:38:57 lanthane avahi-daemon[2502]: Invalid response packet from host 172.23.36.97.
 Jun 11 07:39:56 lanthane avahi-daemon[2502]: Invalid response packet from host 172.23.43.78.
 Jun 11 07:39:56 lanthane avahi-daemon[2502]: Invalid response packet from host 172.23.36.97.

This will become a big problem as apparently Windows 10 causes this.

See also https://bugs.launchpad.net/ubuntu/+source/avahi/+bug/1342400
which references a patch that would help (haven't tested it myself yet,
may do today).

Maybe this bug needs to be merged with #639163
(which is already merged with #688061, although IMHO that's a different
problem).

Paul

**Comment by jmaggard10** [comment]
The patch in that bug deals with OSX mDNS response packets that include Additional RRs, but do not include Answer RRs.

Windows 10 does something different.  It sends responses to *all* mDNS queries, whether or not it has any records for those requests.  That is, it responds with a mDNS packet containing 0 Answer RRs and 0 Additional RRs.  This appears to me to be in violation of RFC 6762 (Multicast DNS) Section 6, which states "A Multicast DNS responder MUST only respond when it has a positive, non-null response to send, or it authoritatively knows that a particular record does not exist."  I don't know how to file a bug with Microsoft, but IMHO this should probably be addressed on their side.

**Comment by jmaggard10** [comment]
Maybe something like this makes sense?
```
diff --git a/avahi-core/server.c b/avahi-core/server.c
index e87f035..18b1c84 100644
--- a/avahi-core/server.c
+++ b/avahi-core/server.c
@@ -972,8 +972,14 @@ static void dispatch_packet(AvahiServer *s, AvahiDnsPacket *p, const AvahiAddres
             return;
         }
 
+        if (avahi_dns_packet_get_field(p, AVAHI_DNS_FIELD_ANCOUNT) == 0 &&
+            avahi_dns_packet_get_field(p, AVAHI_DNS_FIELD_ARCOUNT) == 0) {
+
+            avahi_log_debug("Received empty response packet from host %s.", avahi_address_snprint(t, sizeof(t), src_address));
+            return;
+        }
+
         if (avahi_dns_packet_get_field(p, AVAHI_DNS_FIELD_QDCOUNT) != 0 ||
-            avahi_dns_packet_get_field(p, AVAHI_DNS_FIELD_ANCOUNT) == 0 ||
             avahi_dns_packet_get_field(p, AVAHI_DNS_FIELD_NSCOUNT) != 0) {
 
             avahi_log_warn("Invalid response packet from host %s.", avahi_address_snprint(t, sizeof(t), src_address));
```

**Comment by jgkamat** [comment]
Any progress on this? This has become a huge problem on the network I am on...

**Comment by StuntsPT** [comment]
I second that.
My logs are getting hammered with 20+ of these lines per second...

**Comment by Aeyoun** [comment]
Steps to reproduce in Windows 10:

1. Open Settings app: Devices: Printers and scanners
2. Click Add printers and scanners

Trivia: mDNS is used by printer network stack, and the API is also exposed to WinJS apps (JavaScript based “modern” apps) only. Also available on Windows 10 Mobile.

**Comment by bcomnes** [comment]
Yay! Thanks for solving this long running issue!  Any ideas when it will make it into a release?

**Comment by Aeyoun** [comment]
@bcomnes check the project website at http://avahi.org/

**Comment by Aeyoun** [comment]
The bug have also been [fixed in the latest Windows Insider](https://www.aeyoun.com/technote/windows-mdns-dnssd.html) build. No idea when this stuff will roll out to regular Windows 10 users.

**Comment by bcomnes** [comment]
As I still have windows 7-8 systems on the networks I'm still happy to see this fixed :). Journalctl will be a lot less noisy
