### ISSUE TITLE
SRV records are using compression for the target field, violating RFC 2782

### ISSUE THREAD

**Issue by nathan-osman** [lathiat/avahi#104]
I received a SRV record from Avahi that looks like this:

    0000   c0 2e 00 21 80 01 00 00 00 78 00 17 00 00 00 00
    0010   9f 72 0e 6e 61 74 68 61 6e 2d 64 65 73 6b 74 6f
    0020   70 c0 1d

The target field in particular violates [RFC 2782](https://www.ietf.org/rfc/rfc2782.txt):

    0000   0e 6e 61 74 68 61 6e 2d 64 65 73 6b 74 6f 70 c0
    0010   1d

According to the RFC:

> Unless and until permitted by future standards action, name compression is not to be used for this field.

But as you can clearly see, the target name ends with `c0 [offset]`, signifying a message offset.

**Comment by andrewtj** [comment]
Compressing an SRV target is legal in mDNS. See [RFC 6762](https://tools.ietf.org/html/rfc6762#section-18.14).

**Comment by lathiat** [comment]
Agree that it is legal for mDNS (despite the RFC mention about other record types).

Is this causing you any problems in practice Nathan? From what I can see Bonjour also compresses it with exceptions for publishing wide area records, and curiously transferring records to a sleep proxy server.

**Comment by nathan-osman** [comment]
No, it wasn't causing me problems. Sorry about that. I only noticed it when testing my own implementation against Avahi. I have since corrected my implementation. :smile:

**Comment by evverx** [comment]
Looks like it can be closed.

Technically avahi violates
> In legacy unicast responses generated to answer legacy queries, name
   compression MUST NOT be performed on SRV records.

but I don't think it should cause any problems in 2023.
