### ISSUE TITLE
avahi-daemon: unable to find the introspection data.

### ISSUE THREAD

**Issue by ratagupt** [lathiat/avahi#107]

**Comment by ratagupt** [comment]
Seems avahi-daemon needs the dbus-interfaces at the run time which is not there.

../../avahi-0.6.32/avahi-daemon/chroot.c: open() failed: No such file or directory
Mar 06 02:48:20 palmetto avahi-daemon[689]: Failed to open /usr/share/dbus-1/interfaces/org.freedesktop.Avahi.Server.xml: Invalid argument
avahi-daemon[689]: Failed to load introspection data.

What could be the reason of this failure?
Recipe which is used to build the avahi are as follows.
https://github.com/openbmc/openbmc/blob/master/import-layers/yocto-poky/meta/recipes-connectivity/avahi/avahi.inc#L135

In line no 135 dbus-interfaces directory is being deleted ,is it correct?

**Comment by lathiat** [comment]
Does the file actually exist on your system? at  /usr/share/dbus-1/interfaces/org.freedesktop.Avahi.Server.xml

It should be installed

**Comment by evverx** [comment]
Looks like avahi wasn't installed correctly. Looking at https://github.com/openbmc/openbmc/issues/985 it seems the build script were fixed. Closing.
