### ISSUE TITLE
avahi-autoipd.action.linux should flush previously set IP address

### ISSUE THREAD

**Issue by chombourger** [lathiat/avahi#111]
Noticed that my wlan0 interface ended-up with 2 wlan0:avahi labels, each having a different IPv4LL address. The first IP address got assigned on boot (by udhcpc?), the Bonjour Conformance Tests generate a bunch of conflicts. We eventually get an address and do our BIND. Unfortunately the avahi-autoipd.action.linux is just adding yet another ip address. 

Will submit a PR to clear any IP addresses previously set on the xxx:avahi interface/label

**Comment by evverx** [comment]
Looks like this issue can be closed.

(I came across this issue mostly because that `flush` command came up in https://github.com/lathiat/avahi/pull/462)

**Comment by chombourger** [comment]
indeed. for completeness, here is the PR that got merged a while ago: #112
