### ISSUE TITLE
Return errors from methods, not send after

### ISSUE THREAD

**Issue by zeenix** [lathiat/avahi#121]
The (de-facto) standard way for services to send errors is to do this as part of method return, if the error is from the method itself. Avahi seems to send it afterwards and that makes debugging very difficult. Please see #114 for an implication.

**Comment by evverx** [comment]
It seems to me that it was caused by a D-Bus library that couldn't handle error replies. avahi isn't different here from, say, systemd, fwupd and a bunch of other projects providing D-Bus API. If it wasn't expected there were a lot of bug reports but since the standard D-Bus libraries can handle error replies just fine it has never been brought up (other than in this issue).

The message exchange is straightforward:
```
    6   5.135473       :1.133 → org.freedesktop.Avahi D-Bus 168 AddService() @ /Client0/EntryGroup1
    7   5.136766        :1.68 → :1.133       D-Bus 130 -> org.freedesktop.DBus.Error.AccessDenied
```
where the second message is
```
D-Bus
    Endianness: little-endian
    Message Type: Error reply
    Message Flags: 0x01
        .... ...1 = No Reply Expected: Not expected
        .... ..0. = No Auto Start: Start
        .... .0.. = Allow Interactive Authorization: Don't allow
    Protocol Version: 1
    Message Body Length: 18
    Message Serial: 22
    Header Field Array
        Array Length: 94
        Dict Entry, 6, Destination: :1.133
            Field Code: Destination (6)
            Variant: :1.133
                Variant Signature: s
                Destination: :1.133

        Dict Entry, 4, Error name: org.freedesktop.DBus.Error.AccessDenied
            Field Code: Error name (4)
            Variant: org.freedesktop.DBus.Error.AccessDenied
                Variant Signature: s
                Error name: org.freedesktop.DBus.Error.AccessDenied
        Dict Entry, 5, Reply serial: 2
            Field Code: Reply serial (5)
            Variant: 2
                Variant Signature: u
                Reply serial: 2
        Dict Entry, 8, Signature: s
            Field Code: Signature (8)
            Variant: s
                Variant Signature: g
                Signature: s
        Dict Entry, 7, Sender: :1.68
            Field Code: Sender (7)
            Variant: :1.68
                Variant Signature: s
                Sender: :1.68
    Body
        String: Access denied
```

**Comment by zeenix** [comment]
> It seems to me that it was caused by a D-Bus library that couldn't handle error replies. avahi isn't different here from, say, systemd, fwupd and a bunch of other projects providing D-Bus API

I guess. :) After **6** years I don't have an recollection of this issue what so ever. :) In the meantime, I've created the Rust D-Bus library from scratch and writing a broker in Rust now too. The library in question (dbus-rs) was very much crappy so most likely you're correct.
