### ISSUE TITLE
Vague error on mixing up connections

### ISSUE THREAD

**Issue by zeenix** [lathiat/avahi#122]
If you connect to Avahi with a dbus connection and call Server.EntryGroupNew and then call AddService method on the resulting EntryGroup from the same process using different dbus connections, you get a vague error:

```
Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=52  ReplyCookie=2
  Sender=:1.4  Destination=:1.166
  ErrorName=org.freedesktop.DBus.Error.AccessDenied  ErrorMessage="Access denied"
  UniqueName=:1.4
  MESSAGE "s" {
          STRING "Access denied";
  };
```
This error could be a bit verbose. #121 makes it even harder to debug. See #114 for an implication of these combined.

**Comment by evverx** [comment]
> This error could be a bit verbose

Agreed but this string can't be changed because it's effectively part of the API and some scripts can rely on that somehow (even though they shouldn't).
