### ISSUE TITLE
Service on published interface disappears

### ISSUE THREAD

**Issue by neophob** [lathiat/avahi#129]
Thanks @lathiat for your work. I use avahi (`0.6.32`) on a device with two network interfaces (ethernet and wireless). I discovered a bug that announcing does not work anymore on a network, as soon as a interface (eth0) is coming up. 

Reproduce:
- only wireless interface is connected, avahi publish ip of wlan0
- connect ethernet, avahi publish ip of eth0 but not on wlan0 anymore
- restarting the bonjour daemon fixes this problem (publish on eth0 and wlan0)

Here's the log of my archlinux based system when I connect eth0 (while wlan0 is connected)
```
Jul 04 09:36:59 HOSTNAME systemd-networkd[182]: eth0: Gained carrier
Jul 04 09:36:59 HOSTNAME systemd-timesyncd[163]: Network configuration changed, trying to establish connection.
Jul 04 09:36:59 HOSTNAME kernel: stmmaceth 1c50000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
Jul 04 09:36:59 HOSTNAME systemd-timesyncd[163]: Synchronized to time server 62.149.0.30:123 (1.arch.pool.ntp.org).
Jul 04 09:37:00 HOSTNAME systemd-networkd[182]: eth0: DHCPv4 address 10.0.0.79/24 via 10.0.0.1
Jul 04 09:37:00 HOSTNAME avahi-daemon[8239]: Joining mDNS multicast group on interface eth0.IPv4 with address 10.0.0.79.
Jul 04 09:37:00 HOSTNAME systemd-timesyncd[163]: Network configuration changed, trying to establish connection.
Jul 04 09:37:00 HOSTNAME avahi-daemon[8239]: New relevant interface eth0.IPv4 for mDNS.
Jul 04 09:37:00 HOSTNAME systemd-networkd[182]: eth0: Configured
Jul 04 09:37:00 HOSTNAME avahi-daemon[8239]: Registering new address record for 10.0.0.79 on eth0.IPv4.
```

Here's the log when I disconnect eth0 (while wlan0 is connected). interestingly the avahi does not restart change the listener
```
Jul 04 09:52:11 HOSTNAME systemd-networkd[182]: eth0: Lost carrier
Jul 04 09:52:11 HOSTNAME systemd-networkd[182]: eth0: DHCP lease lost
Jul 04 09:52:11 HOSTNAME systemd-timesyncd[163]: Network configuration changed, trying to establish connection.
Jul 04 09:52:11 HOSTNAME avahi-daemon[8239]: Withdrawing address record for 10.0.0.79 on eth0.
Jul 04 09:52:11 HOSTNAME avahi-daemon[8239]: Leaving mDNS multicast group on interface eth0.IPv4 with address 10.0.0.79.
Jul 04 09:52:11 HOSTNAME avahi-daemon[8239]: Interface eth0.IPv4 no longer relevant for mDNS.
Jul 04 09:52:11 HOSTNAME systemd-timesyncd[163]: Synchronized to time server 95.87.227.232:123 (1.arch.pool.ntp.org).
```

And finally here is the log when I restart avahi:
```
Jul 04 09:54:46 HOSTNAME systemd[1]: Started Avahi mDNS/DNS-SD Stack.
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: Found user 'avahi' (UID 84) and group 'avahi' (GID 84).
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: Successfully dropped root privileges.
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: avahi-daemon 0.6.32 starting up.
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: Loading service file /etc/avahi/services/cp6.service.
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: Joining mDNS multicast group on interface wlan1.IPv4 with address 10.55.12.1.
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: New relevant interface wlan1.IPv4 for mDNS.
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: Joining mDNS multicast group on interface wlan0.IPv4 with address 10.0.0.73.
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: New relevant interface wlan0.IPv4 for mDNS.
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: Joining mDNS multicast group on interface eth0.IPv4 with address 10.0.0.79.
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: New relevant interface eth0.IPv4 for mDNS.
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: Network interface enumeration completed.
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: Registering new address record for 10.55.12.1 on wlan1.IPv4.
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: Registering new address record for 10.0.0.73 on wlan0.IPv4.
Jul 04 09:54:47 HOSTNAME avahi-daemon[8411]: Registering new address record for 10.0.0.79 on eth0.IPv4.
```

any hints how can I prevent, that avahi stops publishing on the wlan0 interface as soon as eth0 is connected?

Update:
Interesting, a `avahi-browse -a` shows that avahi is publishing the entry on all interfaces. however the external view differs...

**Comment by lathiat** [comment]
The most common cause (and it's quite common) I've seen of this I have seen is actually a bad wireless driver that isn't correctly accepting multicast.  In rare cases it has also been filtered by a network switch.

There's a couple of simple tests you can do for this:
 (1) Start tcpdump in non-promiscuous mode and see if the queries are showing up on the network interface.  It's easier to start an "avahi-browse" or similar from another node right after you start tcpdump, as long running queries may not broadcast for 10s of seconds or minutes.  Simple 'tcpdump -ni INTERFACE port 5353'

 (2) After verifying non-promiscuous, try tcpdump in promiscuous mode.  Most drivers with broken multicast will still send the frames through to the host in promiscuous mode.  Use --no-promiscuous-mode -- note that you can't use '-i any' with promiscuous mode.  You need to specify the interface.

**Comment by lathiat** [comment]
I should also add that the reason this often looks like a bug is that initially Avahi broadcasts the service and so all clients receive the advertisement.  However if they don't see the broadcast, and then send out a query for the service they won't get a response.  Further, even nodes that did see the broadcast will then remove those services due to "Passive Observation Of Failure" which actively times out services in the cache for which we don't passively observe responses to queries.

Using Ethernet instead of wireless is often also a quick way to test if the issue is the wireless driver.

**Comment by evverx** [comment]
I think it can be closed.
