### ISSUE TITLE
Please consider using runstatedir

### ISSUE THREAD

**Issue by mbiebl** [lathiat/avahi#137]
autoconf introduced a new directory called runstatedir which is supposed to be used for runtime file:
https://www.gnu.org/prep/standards/html_node/Directory-Variables.html

I think it would make sense to use that for avahi_runtime_dir, so distros wanting to change to /run can build using --runstatedir=/run

**Comment by mbiebl** [comment]
Quoting the relevant bits:

‘runstatedir’
The directory for installing data files which the programs modify while they run, that pertain to one specific machine, and which need not persist longer than the execution of the program—which is generally long-lived, for example, until the next reboot. PID files for system daemons are a typical use. In addition, this directory should not be cleaned except perhaps at reboot, while the general /tmp (TMPDIR) may be cleaned arbitrarily. This should normally be /var/run, but write it as $(localstatedir)/run. Having it as a separate variable allows the use of /run if desired, for example. (If you are using Autoconf 2.70 or later, write it as ‘@runstatedir@’.)

**Comment by lathiat** [comment]
For clarity: 0.7 updated to make /run the default anyway.  Other than this being a generally good idea to change, I'm curious if/how this affects you on the practical side assuming you opened this from the Debian perspective?

**Comment by andhe** [comment]
The debian perspective is that debhelper in (future) debian/compat 11 will start passing --runstatedir=/run by default to all autotools built applications.....
(In other words, I guess @mbiebl just suggested this "for correctness" as I don't see it affecting Debian in any particular way.)

**Comment by smcv** [comment]
You might find this useful (from [dbus' implementation](https://cgit.freedesktop.org/dbus/dbus/commit/?id=1477ca50354a313805690f6c9e581e9d26acefe0)):

```
+# Autoconf 2.70 will support this, and many distros patch this option in,
+# but Autoconf 2.70 hasn't actually been released yet.
+AS_IF([test -z "${runstatedir}"], [runstatedir='${localstatedir}/run'])
+AC_SUBST([runstatedir])
```

That way you can use `${runstatedir}` unconditionally.

**Comment by lathiat** [comment]
That looks great!
