### ISSUE TITLE
python3 configure issues - dbus & gdbm

### ISSUE THREAD

**Issue by andhe** [lathiat/avahi#141]
Hi,

I've ran into a couple of issues when trying to build avahi 0.7 with python3 (and gtk3).

First, AM_CHECK_PYMOD seems to prefer python over python3 so it fails to identify the dbus python module (as only python3-dbus is installed in the build chroot, not python-dbus). This can be worked around by passing the environment variable PYTHON=python3 to the configure call.

Second problem is gdbm python module which apparently there's a patch for in archlinux:
https://git.archlinux.org/svntogit/packages.git/tree/trunk/0001-avahi-python-Use-the-agnostic-DBM-interface.patch?h=packages/avahi

**Comment by andhe** [comment]
Oh, I noticed the patch had already been submitted as https://github.com/lathiat/avahi/pull/134

**Comment by evverx** [comment]
As far as I can tell it can be closed.
