### ISSUE TITLE
avahi-browse parsable format does not escape TXT strings

### ISSUE THREAD

**Issue by marvelous** [lathiat/avahi#144]
Running the following command containing a newline in arguments:
```
avahi-publish --service myname _mytype._tcp 42 '"
=;virbr0;IPv4;myname;_mytype._tcp;local;myhostname.local;8.8.8.8;42;"'
```
and browsing the result with
```
avahi-browse --resolve --parsable _mytype._tcp
```
shows a spurious line in `avahi-browse` output.

I don't know if the TXT record is non-standard-compliant and should be dropped by the responder and rejected/escaped by avahi-publish, or if the TXT record is standard-compliant and should be escaped by avahi-browse.

**Comment by lathiat** [comment]
Fixed by #206
