### ISSUE TITLE
Please revert Pull Request #46

### ISSUE THREAD

**Issue by dkerr64** [lathiat/avahi#150]
Pull request #46 makes this change to configure.ac...
-avahi_runtime_dir="${localstatedir}/run"
+avahi_runtime_dir="/run"

Please back out this change.  Just because "modern, systemd based systems" now use /run instead of /var/run is no reason to HARDCODE /run.  There are other places in the script that use ${localstatedir} that were not updated.  The help information was not updated.  Modern, systemd based systems symlink /var/run to /run so there was no problems with the way it was.

On the other hand it now creates problems for systems that are NOT using /run and/or were passing in a --localstatedir=xxx as part of their build script... which is now ignored (in that one place you made the change).  Now there is no way to pass in a configure parameter to put it back the way it was.

The correct way to do this would have been to have the users that require it to pass in --localstatediir=/. as a configure option.  Or, if it is really necessary to change the default for localstatedir then change the default to "${prefix}/." in the configure script (where it is currently set to "${prefix}/var"

Please revert this pull request.
Thanks
David

**Comment by smcv** [comment]
It looks as though implementing #137 might make everyone happy?
