### ISSUE TITLE
Avahi configuration for domain other than .local

### ISSUE THREAD

**Issue by jamesfreeman959** [lathiat/avahi#155]
Hi there,

Is it possible to get Avahi working for a domain other than ".local". I have been looking into this and noticed the "domain-name" field in /etc/avahi/avahi-daemon.conf

If I set it to an alternative value, the avahi-daemon appears to start correctly - for example:

```
[root@avahi-rhel7-1 ~]# systemctl status avahi-daemon -l
● avahi-daemon.service - Avahi mDNS/DNS-SD Stack
   Loaded: loaded (/usr/lib/systemd/system/avahi-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2017-11-07 16:32:44 GMT; 2h 7min ago
 Main PID: 79314 (avahi-daemon)
   Status: "Server startup complete. Host name is avahi-rhel7-1.qurulabs. Local service cookie is 1678215040."
   CGroup: /system.slice/avahi-daemon.service
           └─79314 avahi-daemon: running [avahi-rhel7-1.qurulabs

Nov 07 16:32:44 avahi-rhel7-1.lab.quru.com avahi-daemon[79314]: Joining mDNS multicast group on interface ens33.IPv6 with address fe80::91f3:5275:c073:9da7.
Nov 07 16:32:44 avahi-rhel7-1.lab.quru.com avahi-daemon[79314]: New relevant interface ens33.IPv6 for mDNS.
Nov 07 16:32:44 avahi-rhel7-1.lab.quru.com avahi-daemon[79314]: Joining mDNS multicast group on interface ens33.IPv4 with address 192.168.81.220.
Nov 07 16:32:44 avahi-rhel7-1.lab.quru.com avahi-daemon[79314]: New relevant interface ens33.IPv4 for mDNS.
Nov 07 16:32:44 avahi-rhel7-1.lab.quru.com avahi-daemon[79314]: Network interface enumeration completed.
Nov 07 16:32:44 avahi-rhel7-1.lab.quru.com avahi-daemon[79314]: Registering new address record for fe80::91f3:5275:c073:9da7 on ens33.*.
Nov 07 16:32:44 avahi-rhel7-1.lab.quru.com avahi-daemon[79314]: Registering new address record for 192.168.81.220 on ens33.IPv4.
Nov 07 16:32:45 avahi-rhel7-1.lab.quru.com avahi-daemon[79314]: Server startup complete. Host name is avahi-rhel7-1.qurulabs. Local service cookie is 1678215040.
```

However if I try and browse the domain, I see:

```
[root@avahi-rhel7-1 ~]# /usr/local/bin/avahi-browse -d qurulabs -a
service_type_browser failed: DNS failure: NXDOMAIN
```

I contacted Red Hat regarding this (as my test environment is RHEL 7) and Red Hat's response was that using a domain other than .local is not possible.

I have built version 0.7 from the source on github and tested it and it seems more stable than the version shipped with RHEL, but I can't figure out the alternate domain option. Is this possible, or am I using avahi in a way in which it was not intended to be used?

Kind regards,

James

**Comment by Bischoff** [comment]
I think you have to use : `lab.quru.com.local`, if I understand the RFC well. Is that an acceptable solution for you?

**Comment by evverx** [comment]
`enable-wide-area` should be set to `no` to get it to work.

> enable-wide-area= Takes a boolean value ("yes" or "no"). Enable wide-
       area DNS-SD, aka DNS-SD over unicast DNS. If this is enabled only do‐
       mains ending in .local will be resolved on mDNS,  all  other  domains
       are  resolved  via unicast DNS. If you want to maintain multiple dif‐
       ferent multicast DNS domains even with this option enabled we encour‐
       age  you  to  use subdomains of .local, such as "kitchen.local". This
       option defaults to "yes".
