### ISSUE TITLE
avahi-gobject: Add a define to fix typo in the API

### ISSUE THREAD

**Issue by smspillaz** [lathiat/avahi#157]
There's a typo in `Avahi.EntryGroupState.GA_ENTRY_GROUP_STATE_COLLISTION` - `COLLISTION` should be `COLLISION`. Possibly a `#define` could be added to fix that?

**Comment by evverx** [comment]
Looks like it was fixed in f74310991d4b349fb74f5d40ed16374814b3631a. Closing.
