### ISSUE TITLE
Debian Avahi package does not scan for mDNS before CIFS automount

### ISSUE THREAD

**Issue by awiebe** [lathiat/avahi#171]
/etc/fstab cifs options execute before all servers have been discovered, so samba servers with mDNS names can't be used as automount drives, until manually running
`mount -a`
after startup is finished.

This can cause other daemons that expect the drives to be available to behave incorrectly.  (e.g. I couldn't figure out why some files wouldn't serve on my web server, only to find out that the asset server hadn't been mounted).

**Comment by evverx** [comment]
It should have been probably reported downstream. The package has changed since then though so I'm not sure if it's still relevant there.
