### ISSUE TITLE
Avahi not advertising local CUPS printers

### ISSUE THREAD

**Issue by supersebbo** [lathiat/avahi#191]
Hi Folks,

I appreciate this is more of a support request than an issue per se, but I'd appreciate the help as I've exhuasted what's googleable. 

I have Avahi and CUPS running on an OpenWRT router to act as an AirPrint proxy for my Samsung printer.   Avahi appears to be working just fine and is advertising the network services as expected - including the native IPP capability of the printer itself.

`= br-lan IPv4 Samsung CLP-670 Series (SEC001599954BCF)      _ipp._tcp            local
   hostname = [SEC001599954BCF.local]
   address = [192.168.1.60]
   port = [631]
   txt = ["Punch=0" "Staple=F" "Sort=F" "Collate=F" "Bind=F" "PaperCustom=T" "Duplex=T" "Copies=F" "Color=T" "Binary=T" "Transparent=T" "MDL=CLP-670 Series" "MFG=Samsung" "adminurl=http://192.168.1.60" "pdl=application/octet-stream,application/postscript,application/x-QPDL" "product=(Samsung CLP-670 Series)" "ty=Samsung CLP-670 Series" "priority=51" "qtotal=1" "txtvers=1"]`

I have also added this printer on the local CUPS server (under a different name 'attic-printer') and can print to it over IPP from a windows client via http://192.168.1.1:631/printers/attic-printer - this I think proves sharing and discovery on CUPS works just fine. 

However for some reason Avahi cannot find this printer service at all, or any other printers shared on this local cups server. 

Any ideas why this will not work?

Thanks

**Comment by evverx** [comment]
My guess would be that the printer wasn't announced over mDNS because the CUPS server wasn't configured to do that but it's hard to tell. I think https://wiki.archlinux.org/title/CUPS/Printer_sharing can help to find out what should be enabled to make it all work. Closing.

**Comment by evverx** [comment]
> Avahi appears to be working just fine and is advertising the network services as expected
> ...
> Avahi cannot find this printer service at all, or any other printers shared on this local cups server

To judge from that it was advertised somewhere though but I'm not sure where the second instance of avahi (which was unable to find services) was run. Either way I think it should probably be first reported/asked on the CUPS mailing lists/forums to make sure it's configured correctly and if it's configured correctly it should probably be possible to figure out where avahi is involved (with avahi configs/debug logs/pcaps on all the participating machines attached).
