### ISSUE TITLE
.lan domain aren't resolved

### ISSUE THREAD

**Issue by Faelian** [lathiat/avahi#199]
Hello,

I am not sure if this is a distribution issue, or an issue with avahi. But I guess I have to report this bug somewhere :) .

I have noticed that on Ubuntu 16.04, DNS resolution of "local domain names" (ex : corporate**.lan**) fail when avahi-daemon is up. But .lan domain names are correctly resolved when avahi-daemon is down.

**Comment by lathiat** [comment]
What is the contents of your /etc/nsswitch.conf?

This shouldn't happen, I doubt it's a bug though, probably a misconfiguration at a guess.

**Comment by lathiat** [comment]
And to be clear can you confirm the *exact* hostname you are having problems resolving (the entire thing)

**Comment by evverx** [comment]
There has been no response since 2018. Closing.
