### ISSUE TITLE
Chromecast Disappear

### ISSUE THREAD

**Issue by juliodiz** [lathiat/avahi#200]
My chromecast is only showing up for a few seconds on the iphone and disappears.
I am using it on another subnet with the reflector. I can not cast youtube, netflix, etc.

+ eth1 IPv4 Chromecast-XXXXX _googlecast._tcp local
- eth1 IPv4 Chromecast-XXXXX _googlecast._tcp local

How can I prevent avahi from removing my chromecast?

**Comment by evverx** [comment]
I'm afraid it's hard to tell without logs/configs/pcaps and so on. My guess would be that it's https://github.com/lathiat/avahi/issues/379 but it can be something else entirely. I guess one option would be to replace avahi with https://github.com/geekman/mdns-repeater to see whether it helps. If it doesn't help the issue probably has nothing to do with avahi. If it works with mdns-repeater it should be possible to apply the kludge from https://github.com/lathiat/avahi/issues/379 preventing avahi from reflecting NSEC RRs to figure out whether those malformed NSEC RRs cause this issue. Either way I'll go ahead and close it. If it's still relevant could you open a new issue and attach avahi configs, debug logs (they can be turned on by passing the `--debug` option) and pcaps showing mDNS packets in the subnets?
