### ISSUE TITLE
server.c:1718]: (style) Suspicious condition 

### ISSUE THREAD

**Issue by dcb314** [lathiat/avahi#205]
server.c:1718]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.

Source code is

  if ((ret = avahi_service_name_join(n, sizeof(n), name, type, domain) < 0))

Maybe better code

  if ((ret = avahi_service_name_join(n, sizeof(n), name, type, domain)) < 0)

**Comment by evverx** [comment]
Looks like it's a bug. Would you mind sending a PR with the suggested change? It should make avahi set the actual error code as far as I can see.

**Comment by evverx** [comment]
On a somewhat related note it would probably make sense to turn on a cppcheck GH action to catch things like this automatically when PRs are opened.

**Comment by evverx** [comment]
@jamacku I wonder if https://github.com/redhat-plumbers-in-action/differential-cppcheck works or did you end up using something else?

**Comment by jamacku** [comment]
> @jamacku I wonder if https://github.com/redhat-plumbers-in-action/differential-cppcheck works, or did you end up using something else?
> 
> Edit: looks like there is no code there. My bad. I'll keep looking.

@evverx, It was just an idea when I started with differential shellcheck, but I never realized it. Sorry

**Comment by evverx** [comment]
@jamacku that's okay. cppcheck is on the back burner anyway :-)

Having spent some time asking for configs/logs/pcaps in issues like https://github.com/lathiat/avahi/issues/518 like it's 1998 again I'm planning to add issue templates with the issue labeler first but I haven't figured out what they should look like :-)

In the meantime the suggested fix was merged: https://github.com/lathiat/avahi/commit/16b6397f15b28ec80d57a892a7f982aad7630e0f

**Comment by jamacku** [comment]
> I'm planning to add issue templates with the issue labeler first but I haven't figured out what they should look like :-)

@evverx, Feel free to ping me if you need help or If something doesn't work.

**Comment by evverx** [comment]
For the record looks like cppcheck is included in OpenScanHub and probably the "clarifyCondition " check can be flipped there: https://github.com/packit/packit/discussions/2371. Looking at https://github.com/avahi/avahi/pull/635 I'm starting to think that it should be run automatically :-)
