### ISSUE TITLE
Is it possible to use avahi-autoipd with the official mDNSResponder by Apple?

### ISSUE THREAD

**Issue by Ks89** [lathiat/avahi#209]
Hi!

Is it possibile to run avahi-autoipd to have full RFC 3927 support without the rest of Avahi, but using the official mdns package from Apple?
Because I'm trying to use Apple mdns, but I cannot manage ipv4 local link in the right way.

Do you have any suggestions? Thank u.

**Comment by lathiat** [comment]
You can absolutely use avahi-autoipd without the rest of avahi. It is an independent daemon.

Alternatively if you look at sytemd-networkd it also includes support for this.
