### ISSUE TITLE
Take translations from Transifex before each release

### ISSUE THREAD

**Issue by scootergrisen** [lathiat/avahi#215]
Its unclear how to submit translations for Avahi.

In https://github.com/lathiat/avahi/commit/14693c41460827e37aa182c59067a96206030ea5 it seems like the translations was automatically taken from Transifex before a release.
But then the following two realese might not have done that.

So i suggest taking translations automatically from Transifex before each release or if you dont want to use Transifex anymore then take the translations and close the translations on Transifex so translators are not confused.

**Comment by evverx** [comment]
Looking at https://explore.transifex.com/search/?q=avahi I'm not sure avahi is on Transifex anymore. I guess the issue can be closed. Sorry.

It would probably be nice to set something up. I'd probably opt for Weblate because it can automatically open PRs but I'm not sure it's worth it.
