### ISSUE TITLE
avahi link local address sometimes changes after restarting

### ISSUE THREAD

**Issue by pawelevans** [lathiat/avahi#228]
Avahi is installed on an embedded device.  If there is no dhcp server on the network, the device selects a link-local address i.e 169.254.x.x, probes the network to ensure not already used by another host and then assigns it.  According to the standard a device with a previously recorded address should first use that address when probing.
However, I am finding that occasionally avahi on my device occasionally selects a different link-local IP address after restarting, despite there being no other conflicting addresses on the network.

Any advice on why this is happening, and if its possible to make it fixed always (when no conflict), would be much appreciated.

**Comment by dtychero** [comment]
Hi @pawelevans , could you please refer to the source that says it should use the prerecorded address?
As far as I know the standard says that the IP selection should be pseudorandom following a uniform distribution and seeded with a unique piece of information of the device (e.g. MAC address)
[https://tools.ietf.org/html/rfc3927]
)(page 9, **2.1.  Link-Local Address Selection**)

**Comment by pawelevans** [comment]
Hi @dtychero - thanks for your reply.   I have found the cause of why avahi sometimes uses a different address and it is correctly following the standard.  For anyone else with the same issue, below is my conclusion:

Devices do reliably generate the same link-local address on reboot UNLESS during the probing sequence there is an arp request packet from another device (a peer device or the dau) to the address being probed for.

This is standard practice, as per the following extract from RFC3927:
A host probes to see if an address is already in use by broadcasting
   an ARP Request for the desired address.  The client MUST fill in the
   'sender hardware address' field of the ARP Request with the hardware
   address of the interface through which it is sending the packet.  The
   'sender IP address' field MUST be set to all zeroes, to avoid
   polluting ARP caches in other hosts on the same link in the case
   where the address turns out to be already in use by another host.

   The 'target hardware address' field is ignored and SHOULD be set to
   all zeroes.  The 'target IP address' field MUST be set to the address
   being probed.  An ARP Request constructed this way with an all-zero
   'sender IP address' is referred to as an "ARP Probe".
   
   When ready to begin probing, the host should then wait for a random
   time interval selected uniformly in the range zero to PROBE_WAIT
   seconds, and should then send PROBE_NUM probe packets, each of these
   probe packets spaced randomly, PROBE_MIN to PROBE_MAX seconds apart.
   If during this period, from the beginning of the probing process
   until ANNOUNCE_WAIT seconds after the last probe packet is sent, the
   host receives any ARP packet (Request *or* Reply) on the interface
   where the probe is being performed where the packet's 'sender IP
   address' is the address being probed for, then the host MUST treat
   this address as being in use by some other host, and MUST select a
   new pseudo-random address and repeat the process.  In addition, if
   during this period the host receives any ARP Probe where the packet's
   'target IP address' is the address being probed for, and the packet's
   'sender hardware address' is not the hardware address of the
   interface the host is attempting to configure, then the host MUST
   similarly treat this as an address conflict and select a new address
   as above.  This can occur if two (or more) hosts attempt to configure
   the same IPv4 Link-Local address at the same time.

**Comment by evverx** [comment]
Looks like it can be closed.
