### ISSUE TITLE
Avahi problems when interface address record is withdrawn and added again

### ISSUE THREAD

**Issue by hsebert** [lathiat/avahi#234]
In our network setup (LXD container with bridged network interface), when a DHCP request is made in the background, Avahi withdraws the corresponding address record and immediately adds it again afterwards. The corresponding piece of the Avahi log file looks as follows:
```
...
Withdrawing address record for 10.96.192.235 on bridge.
Leaving mDNS multicast group on interface bridge.IPv4 with address 10.96.192.235.
Interface bridge.IPv4 no longer relevant for mDNS.
Joining mDNS multicast group on interface bridge.IPv4 with address 10.96.192.235.
New relevant interface bridge.IPv4 for mDNS.
Registering new address record for 10.96.192.235 on bridge.IPv4.
...
```
This by itself is not a problem. However, when this happens during Avahi server start-up or during service registration, Avahi either does not come up at all (does not leave the AVAHI_REGISTERING state) or service registration fails (the corresponding entry group does not leave the AVAHI_ENTRY_GROUP_REGISTERING state).

When digging into the issue I found out that the corresponding entry groups do not leave the probing state. I fixed this problem in Pull Request #233 

I would appreciate any comments or feedback on this! Thanks!

**Comment by marc-h38** [comment]
Related to #117?
