### ISSUE TITLE
Problem with avahi configuration

### ISSUE THREAD

**Issue by FrancescoDeSimone** [lathiat/avahi#235]
Hi,
I install avahi on a raspberry pi to be able to detect it with mdns. 
The service is up:
```
● avahi-daemon.service - Avahi mDNS/DNS-SD Stack
   Loaded: loaded (/lib/systemd/system/avahi-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2019-07-14 11:18:32 BST; 16min ago
 Main PID: 4213 (avahi-daemon)
   Status: "avahi-daemon 0.7 starting up."
    Tasks: 2 (limit: 2200)
   Memory: 660.0K
   CGroup: /system.slice/avahi-daemon.service
           ├─4213 avahi-daemon: running [rasbperrypi.local]
           └─4214 avahi-daemon: chroot helper

Jul 14 11:18:32 raspberrypi avahi-daemon[4213]: Joining mDNS multicast group on interface eth0.IPv6 with address 2001:b07:6455:5fd5:dafa:2ec4:2d60:93e8.
Jul 14 11:18:32 raspberrypi avahi-daemon[4213]: New relevant interface eth0.IPv6 for mDNS.
Jul 14 11:18:32 raspberrypi avahi-daemon[4213]: Joining mDNS multicast group on interface eth0.IPv4 with address 192.168.1.80.
Jul 14 11:18:32 raspberrypi avahi-daemon[4213]: New relevant interface eth0.IPv4 for mDNS.
Jul 14 11:18:32 raspberrypi avahi-daemon[4213]: Network interface enumeration completed.
Jul 14 11:18:32 raspberrypi avahi-daemon[4213]: Registering new address record for 2001:b07:6455:5fd5:dafa:2ec4:2d60:93e8 on eth0.*.
Jul 14 11:18:32 raspberrypi avahi-daemon[4213]: Registering new address record for 192.168.1.80 on eth0.IPv4.
Jul 14 11:18:33 raspberrypi avahi-daemon[4213]: Server startup complete. Host name is rasbperrypi.local. Local service cookie is 3290297512.
Jul 14 11:18:34 raspberrypi avahi-daemon[4213]: Service "rasbperrypi" (/services/ssh.service) successfully established.
Jul 14 11:18:34 raspberrypi avahi-daemon[4213]: Service "rasbperrypi" (/services/multiple.service) successfully established.
```
I also create a service for ssh connection:
```
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">%h</name>
  <service>
    <type>_ssh._tcp</type>
    <port>22</port>
  </service>
</service-group>

```
The problem is ping doesn't find the raspberry at the address raspberrypi.local  but raspberrypi.lan, and tools like mdns-scan and doesn't see the raspberry.
I need to search for all ssh devices in my network, how can i solve this?

EDIT:
this is my /etc/nsswitch.conf
```
passwd:         compat
group:          compat
shadow:         compat
gshadow:        compat

hosts:          files mdns4_minimal [NOTFOUND=return] dns
raspberrypi
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

**Comment by lathiat** [comment]
For whatever reason your hostname has the b and p reversed. 

Seems like it’s spelt wrong somewhere and only partly fixed?

**Comment by lathiat** [comment]
4213 avahi-daemon: running [rasbperrypi.local]

**Comment by FrancescoDeSimone** [comment]
@lathiat also with rasbperrypi.local notting. Sorry for the error

**Comment by lathiat** [comment]
For clarity when you go "ping raspberrypi" it's using LLMNR or something else (such as local DNS form your DNS server) to do the lookup - and the hostname you see in the reply (raspberrypi.lan) is related to the reverse DNS lookup which for non-link-local subnets won't be mDNS.

Avahi will only get involved if you specifically ping a .local domain, and then, it will only work if you have libnss-mdns installed and avahi running. To confirm mDNS is working, i'd suggest running "avahi-resolve-host-name rasbperrypi.local" from another machine (trying both variants of the hostname); and you could also try 'avahi-browse -a' - if that works but ping doesn't, something is preventing your libnss-mdns from working properly.

**Comment by dpdhole** [comment]
Same problem multiple rpi using buster.

Un commenting the following 2 lines from [server] section of /etc/avahi/avahi-daemon.conf and restarting the avahi-daemon service resolved the issue.

host-name=rpizero
domain-name=local

**Comment by evverx** [comment]
I think it can be closed.

If there are still issues https://github.com/lathiat/avahi/issues/235#issuecomment-511305697 should help to at least triage them and provide more details:
> Avahi will only get involved if you specifically ping a .local domain, and then, it will only work if you have libnss-mdns installed and avahi running. To confirm mDNS is working, i'd suggest running "avahi-resolve-host-name rasbperrypi.local" from another machine (trying both variants of the hostname); and you could also try 'avahi-browse -a' - if that works but ping doesn't, something is preventing your libnss-mdns from working properly.
