### ISSUE TITLE
enable-dbus=no causes avahi errors

### ISSUE THREAD

**Issue by nraygun** [lathiat/avahi#237]
I tried to add "enable-dbus=no" to the avahi config file /etc/avahi/avahi-daemon.conf and it produces the following symptoms:
1. Chrome takes awhile to load its list of printers. But when it does, no ghost printers.
2. I get errors in the system journal like this:
```
Jul 29 17:08:42 mxlinux systemd[1]: Failed to start Avahi mDNS/DNS-SD Stack.
-- Subject: Unit avahi-daemon.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit avahi-daemon.service has failed.
```
This is on Xubuntu 18.04.2 with avahi-daemon 0.7

I am trying to add this parameter to see if it addresses a "ghost printer" symptom where a non-working printer appears in printing UIs in various applications.
Removing "enable-dbus=no" restores speedy response in Chrome and no journal errors but then the "ghost printer" comes back.

**Comment by nraygun** [comment]
On another system (MX Linux), avahi 0.6 doesn't seem to have these problems.

**Comment by nraygun** [comment]
Hello? Is this thing on? ;-)

**Comment by aaron-sonin** [comment]
I have this issue too.

**Comment by macieksk** [comment]
I am experiencing the same problem, too.

**Comment by nraygun** [comment]
I just checked again since I reloaded Xubuntu and I'm now on 18.04.3 and I still get the same problem. Adding "enable-dbus=no" to the avahi config file doesn't seem to work and causes delays.

**Comment by macieksk** [comment]
According to [this](https://bugs.launchpad.net/ubuntu/+source/avahi/+bug/1507247) avahi requires dbus enabled for status checking. I'll go with disabling avahi for now.

**Comment by playaspec** [comment]
If "enable-dbus=no" breaks Avahi in all cases, why is this even an option? Many embedded systems lack the resources of desktop and server Linux systems, and dispense with systems like d-bus entirely. What is this option good for, and what is the solution for systems that don't have d-bus?

**Comment by evverx** [comment]
The avahi service file has to be changed to get it to work without D-Bus: https://github.com/lathiat/avahi/issues/284#issuecomment-873334519. Closing.
