### ISSUE TITLE
Airplay2 not working

### ISSUE THREAD

**Issue by KleBoR** [lathiat/avahi#242]
Hi,

Is there a known issue with the airplay2 support?
If i connect to airplay2 clients and start playing some music the connection drops after 2-4 seconds without hearing any sound.

Any help is appreciated, thank you!

Greetings

**Comment by evverx** [comment]
It's hard to tell what the issue is. I'm not even sure if avahi was involved there. If it's still relevant please open a new issue and attach logs/configs/pcaps.
