### ISSUE TITLE
assert after avahi_s_entry_group_reset

### ISSUE THREAD

**Issue by dbHmpf** [lathiat/avahi#244]
Hi!

I'm using avahi 0.6.32 on a Blackfin controller in a custom avahi daemon. 
When updating services (changing service name) first the group is reset using avahi_s_entry_group_reset.
Then my services are recreated (avahi_server_add_service) followed by a commit (avahi_s_entry_group_commit).

Not always but regularly I'll see different assertions.
(avahid is my daemon).

> /firmware/avahid: response-sched.c: 285: find_scheduled_job: Assertion `rj->state == AVAHI_SCHEDULED' failed.

> /firmware/avahid: response-sched.c: 116: job_free: Assertion `*_head == _item' failed.

> /firmware/avahid: rr.c: 370: rdata_equal: Assertion `a->key->type == b->key->type' failed.

>/firmware/avahid: prioq.c: 357: avahi_prio_queue_remove: Assertion `!n->left' failed.

The daemon crashes.
The goodbye messages are sent. The service announcements are not.

Is their anything else you'd like to know?

Regards
Sebastian

**Comment by evverx** [comment]
`avahi_s_entry_group_reset` followed by `avahi_server_add_service` and `avahi_s_entry_group_commit` is regularly tested on the CI with plain builds and also under ASan/UBSan and Valgrind and nothing seems to crash. If it's still relevant could you open a new issue and attach code that can be compiled and used to reproduce those crashes with the master branch of avahi?
