### ISSUE TITLE
avahi-daemon segfaults when a txt-record has no value

### ISSUE THREAD

**Issue by kirichkov** [lathiat/avahi#247]
Version: avahi-daemon 0.7 on Raspbian Buster

Service XML causing the segfault:

```xml
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">Printer</name>
  <service protocol="ipv4">
    <type>_ipp._tcp.</type>
    <host-name>printer.local</host-name>
    <port>631</port>
    <txt-record>note=</txt-record>
  </service>
</service-group>
```

The line `<txt-record>note=</txt-record>` causes avahi to segfault. That did not happen on previous version of Raspbian.

The Workaround I found was: `<txt-record>note=""</txt-record>` I.e. setting the `note` to an empty string.

**Comment by lathiat** [comment]
Merged
