### ISSUE TITLE
avahi stop reply after 1 minute

### ISSUE THREAD

**Issue by jmforum** [lathiat/avahi#259]
I use avahi v0.7 compiled with buildroot 2019.02 to armv7 target. The compilation works fine.

After service start or system start, I can ping (from other computer) my device with `ping wpb-the.local`. But after few minutes 1 or 2 (on the same computer) I got` ping: wpb-the.local: Name or service not known from Ubuntu` or `Ping request could not find host wpb-the.local. Please check the name and try again.` from windows. But with the ip address there is no problem.

On device side the daemon still running and there is no error in messages. And if I stop the service and restart it, then it's working during few minutes again.

I don't understand why. Do you have any hint ?

I try to start daemon with debug, this is log result
```
# /usr/sbin/avahi-daemon --debug
Found user 'avahi' (UID 1000) and group 'avahi' (GID 1000).
Successfully dropped root privileges.
avahi-daemon 0.7 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Loading service file /etc/avahi/services/sftp-ssh.service.
Loading service file /etc/avahi/services/ssh.service.
Joining mDNS multicast group on interface eth1.IPv6 with address fe80::217:4cff:fe1e:102.
New relevant interface eth1.IPv6 for mDNS.
Joining mDNS multicast group on interface eth1.IPv4 with address 10.150.67.8.
New relevant interface eth1.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::217:4cff:fe1e:102 on eth1.*.
Registering new address record for 10.150.67.8 on eth1.IPv4.
Server startup complete. Host name is wpb-the.local. Local service cookie is 2229292744.
Service "wpb-the" (/etc/avahi/services/ssh.service) successfully established.
Service "wpb-the" (/etc/avahi/services/sftp-ssh.service) successfully established.
```
Best regards

JM

**Comment by lathiat** [comment]
This generally means that multicast traffic is not arriving to the avahi machine. Either bad NIC driver (broken multicast), firewall or in rare cases blocked on the network side. 

I suggest you try tcpdump with and without promiscuous mode to see if the packets are arriving or not in both cases. In promiscuous mode it will usually “fix” a broken network driver as it causes all packets including multicast to be sent to the kernel. So if it works while a promiscuous tcpdump is running that’s likely the issue.

**Comment by jmforum** [comment]
Thanks @lathiat, that was a firewall trouble, after disable it, or open udp 5353, it's works. 
Best Regards

**Comment by frazarz80** [comment]
Please unsubscribe me from your mailing list
