### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by hostmit** [lathiat/avahi#261]
Hi! How do I compile from source?
autogen.sh hangs forever on debian 10

**Comment by RFRIEDM-Trimble** [comment]
https://github.com/lathiat/avahi/blob/master/docs/INSTALL#L7

Also trying the `configure` script fails as explained.

**Comment by evverx** [comment]
I'm not sure why it didn't work two years ago but I've just launched a Debian 10 container and built avahi there.

More generally https://salsa.debian.org/utopia-team/avahi/-/blob/debian/master/debian/control and https://salsa.debian.org/utopia-team/avahi/-/blob/debian/master/debian/rules can be used to figure out how the official Debian package is built and `apt-file` can be used to locate the other dependencies like https://github.com/lathiat/avahi/issues/291 if necessary.

I'll go ahead and close this. If it still fails to build for whatever reason it should be possible to open another issue and provide more details.
