### ISSUE TITLE
Select publishing of specific IP address for the same interface

### ISSUE THREAD

**Issue by ondrej1024** [lathiat/avahi#269]
I have a network interface with multiple IP addresses (1 static address and 1 obtained via DHCP). All of these addresses are registered by avahi.

```
Feb 26 12:58:33 smarthub avahi-daemon[277]: Registering new address record for 192.168.100.250 on eth0.IPv4.
Feb 26 12:58:33 smarthub avahi-daemon[277]: Registering new address record for 192.168.10.116 on eth0.IPv4.

```
So my first question is: which address will be published, the first in the list?

I see that I can deny publishing any address of a specific interface via the `deny-interfaces` parameter in the configuration file.

So my second question is: is it also possible to select which specific address will be published?

It would be great if someone could help me with this.
Thanks, Ondrej

**Comment by ondrej1024** [comment]
Anyone ?

**Comment by EskoDijk** [comment]
@ondrej1024 See the mDNS RFC, Section 6.2 https://www.rfc-editor.org/rfc/rfc6762#section-6.2 
It is mandatory (MUST) for interoperability to include all addresses so a selection ought not to be done. (Maybe only for debugging purposes, with a special API function or so)

See also issue #243 https://github.com/lathiat/avahi/issues/243 

So I think this issue can be closed as the feature request should not be granted, and the question is answered by #243 . But if you disagree feel free to respond!

**Comment by ondrej1024** [comment]
OK to close.
