### ISSUE TITLE
avahi-daemon/introspect.dtd AFL 1.1 license

### ISSUE THREAD

**Issue by joseph-reynolds** [lathiat/avahi#283]
File [avahi-daemon/introspect.dtd](https://github.com/lathiat/avahi/blob/master/avahi-daemon/introspect.dtd) is licensed per a comment in the file which states: `released under the D-BUS licenses, GNU GPL version 2 (or greater) and AFL 1.1 (or greater)`.

I interpret AFL 1.1 to refer to the "Academic Free License v1.1" [SPDX ID AFL-1.1](https://spdx.org/licenses/AFL-1.1.html).  The AFL 1.1 license doesn't meet my needs but I can accept AFL 3.0 [SPDX ID AFL-3.0](https://spdx.org/licenses/AFL-3.0.html)

Does the license statement in the file mean I can choose to comply with AFL-3.0 instead of AFL-1.1?  If this interpretation works for everyone, then I can use Avahi as-is and I can close this issue.

Otherwise, can you tell me how to use Avahi without this file?

**Comment by joseph-reynolds** [comment]
@poettering Is there any progress on this?
Note that my project (https://github.com/openbmc/openbmc) does not use the avahi introspect feature, so I would be happy with a technical solution such that the build process does not use the introspect.dtd file.  Can you help make that solution work?

**Comment by evverx** [comment]
> Does the license statement in the file mean I can choose to comply with AFL-3.0 instead of AFL-1.1?

I think it would be better to contact actual lawyers if there are any concerns regarding this statement. Closing.
