### ISSUE TITLE
no /run directory on root for tomato routers and relatives, so no pid directory.....

### ISSUE THREAD

**Issue by skwysham** [lathiat/avahi#285]
Re: tomato router and related application: The avahi-daemon directory that is hard coded in configure.ac cannot be created by the daemon because there is no writable /run, or link to one, existing on the filesystem and the root filesystem is read-only.

from the log
daemon.err avahi-daemon[31228]: mkdir("/run/avahi-daemon/"): No such file or directory

/tmp/home/root# ls /
bin       cifs1     dev       home      lib       mnt       opt       rom       sbin      tftpboot  usr       www
bkp       cifs2     etc       jffs      mmc       nas       proc      root      sys       tmp       var

This maybe superfluous info, but the "early" builds of linux do not have a /run directory by default. Maybe, for consistency's sake, the filesystem can be built with link /run pointing to /tmp/run?  But, that's not in your court, I guess.

**Comment by evverx** [comment]
Looks like it's a variation on https://github.com/lathiat/avahi/issues/150.
