### ISSUE TITLE
Don't use embedded code copy of sd-daemon.[ch]

### ISSUE THREAD

**Issue by mbiebl** [lathiat/avahi#287]
In the early days of libsystemd/systemd, embedding sd-daemon.[ch] was an approach recommended by upstream. This is no longer the case. Since libsystemd has matured, nowadays it's better to link against libsystemd instead.

**Comment by pemensik** [comment]
Just hit it during SPDX license evaluation. Yes, these should instead use libsystemd. Not bundling the code itself.
./avahi-daemon/sd-daemon.c      Expat
./avahi-daemon/sd-daemon.h      Expat

**Comment by evverx** [comment]
I'll revert that PR shortly.
