### ISSUE TITLE
Missing link causes avahi to not be started on demand by systemd when needed

### ISSUE THREAD

**Issue by pacho2** [lathiat/avahi#29]
On Gentoo, Arch and many other distributions we are needing to provide this missing link to get avahi started automatically on demand by systemd when needed:
ln -s avahi-daemon.service /usr/lib/systemd/system/dbus-org.freedesktop.Avahi.service

Thanks

**Comment by lathiat** [comment]
According to the following URL:
https://fedoraproject.org/wiki/Packaging:Systemd#DBus_activation


> Note that the creation/removal of the alias symlinks should be done with "systemctl enable" and "systemctl disable" only. You should not create these symlinks manually

From reading that I would suggest the "proper" fix is to run systemctl enable during post-install to install the symlink.  Thoughts?

**Comment by pacho2** [comment]
Well, the problem is how to ensure make install will provide the link as, otherwise, people will simply see in the logs that the service is failing to start because of "No such file or directory" :/

Or maybe it could show a warning at the end (I bit like it's done in some packages for remembering people to run update-mime-database and similar)

**Comment by pacho2** [comment]
I have sent a mail to systemd list, hopefully they will know :)
http://lists.freedesktop.org/archives/systemd-devel/2015-October/034736.html

**Comment by lathiat** [comment]
Thanks.. based on the reply we should probably update this file with one closer to the Fedora version.

> by the Also/Alias in the install section of proper units like the Fedora ones
> [root at srv-rhsoft:~]$ cat /usr/lib/systemd/system/avahi-daemon.service
> [Unit]
> Description=Avahi mDNS/DNS-SD Stack
> Requires=avahi-daemon.socket
>
> [Service]
> Type=dbus
> BusName=org.freedesktop.Avahi
> ExecStart=/usr/sbin/avahi-daemon -s
> ExecReload=/usr/sbin/avahi-daemon -r
> NotifyAccess=main
>
> [Install]
> WantedBy=multi-user.target
> Also=avahi-daemon.socket
> Alias=dbus-org.freedesktop.Avahi.service

**Comment by pacho2** [comment]
Per the following comments in the mailing list, it seems that we should go with the Fedora way of doing it... even if it seems people will need to still manually enable avahi :/

**Comment by lathiat** [comment]
I'm confused as to why your distribution script cannot run this command, to 'automate' the process (nothing manual required).  I don't think it makes sense to automate this in "make install" but it makes perfect sense during package installation (depending of course, on the policy if your distribution.. Debian seems to almost always auto-start things, fedora is a bit more so-so about that).

**Comment by pacho2** [comment]
Well, in our case (Gentoo) we support at least two init systems (systemd and openrc), then, we cannot enable it blindly. Even for setups running systemd, we don't think it's ok to automatically enable a service a user would not be aware of. What it's a non sense to me is that, if we don't enable the service to get it running *all the time*, people will simply get a "no such file or directory" failure when systemd tries to spawn avahi but it cannot do that because of the link being missing :/

**Comment by lathiat** [comment]
OK I think I understand your concern now.. the issue is that basically you cannot do "start" without first doing "enable", am I right?

**Comment by pacho2** [comment]
It looks like systemd cannot start it automatically without the link... it's like a nonsense to me :/

Using the link is "bad" because... some kind if policy, but systemd tries to use that link to start it *when needed* 

On the other hand, they force people to "enable" the service (and, then, having it enabled always) to get it started :|

**Comment by michaellass** [comment]
I assume this has never really been solved, right? To me it seems that avahi's dbus activation is clearly broken. There are two cases to consider:

1. `avahi-daemon.service` has _not_ been enabled via systemd. Then dbus activation via `org.freedesktop.Avahi.service` cannot work because that file says `SystemdService=dbus-org.freedesktop.Avahi.service`. However, the alias `dbus-org.freedesktop.Avahi.service` is not known to systemd because that symlink is only created when `avahi-daemon.service` is enabled.
2. `avahi-daemon.service` _has_ been enabled via systemd. The dbus activation would work because the alias is known. However, it is basically unnecessary because `avahi-daemon.service` is anyway automatically started at boot up.

So, currently there is no way to have `avahi-daemon.service` _only_ be started when requested via dbus.

**Comment by evverx** [comment]
> it is basically unnecessary because avahi-daemon.service is anyway automatically started at boot up

It can go down for whatever reason in the process and if it is enabled it can be started again via D-Bus so clients using D-Bus API can somewhat fix transient issues.

> systemd uses a very similar pattern for several of its services

It doesn't use it for services receiving network packets like `resolved`, `networkd` and `timesyncd` and `avahi` falls into that category. If it isn't enabled explicitly it's unlikely that the firewall and the network interfaces are set up either.

I think it can be closed.
