### ISSUE TITLE
is it still possible to do screen mirroring from iPhone to Ubuntu18.04

### ISSUE THREAD

**Issue by cpagrawal** [lathiat/avahi#290]
I was working on this for a while. avahi-daemon is working perfectly and service is running on Ubuntu but I can not see any option for screen mirror on my iPhone and I found an article : 
https://www.macobserver.com/news/product-news/apps-cant-view-mac-addresses-on-ios-11/

is it still possible to do screen mirroring ?

**Comment by elearningdienst** [comment]
I think it is related to https://github.com/lathiat/avahi/issues/262

**Comment by evverx** [comment]
I'm afraid this issue isn't actionable. If it still happens (and has anything to do with avahi) please open a new issue with configs/logs/pcaps attached.
