### ISSUE TITLE
Debian : Qt5Core equivalent ?

### ISSUE THREAD

**Issue by ChameleonScales** [lathiat/avahi#291]
Hi,
Trying to run autogen.sh, I get a `No package 'Qt5Core' found`
I believe the Debian name for that package is libqt5core5a because its description says "Qt 5 core module". I have it installed but it still throws me the error.

Any idea what I can do?

Debian version : 10.4

**Comment by evverx** [comment]
`qtbase5-dev` should be installed to get it to work. More generally
```
apt-file update
apt-file search 'Qt5Core.pc'
```
should help to locate the package.
