### ISSUE TITLE
Multi-threading with avahi_service_resolver_new()

### ISSUE THREAD

**Issue by mohitmo** [lathiat/avahi#295]
Hi there
I have a function running in a separate thread from main, that calls `avahi_service_resolver_new()` and we need the callback of it to run in same thread as of `avahi_service_resolver_new()`, but the problem is that the callback is not running in the same thread, but is actually running in the main thread.
So is there a way to make sure that `avahi_service_resolver_new()` and its callback runs in the same thread, which is separate from the main thread?

**Comment by lathiat** [comment]
The callback happens based on your main loop integration (AvahiPoll). Whatever thread is executing the main loop callbacks is what will call into your callbacks.  

That’s the avenue you’d have to work on to make that happen, eg you need to have a main loop implementation running in that thread.
