### ISSUE TITLE
avahi-daemon/sd-daemon.c: outdated (non-working) systemd check 

### ISSUE THREAD

**Issue by ovitters** [lathiat/avahi#296]
avahi-daemon/sd-daemon.c seems to be copied ages ago from systemd. It checks if systemd is running by looking at the following paths:

- /sys/fs/cgroup
- /sys/fs/cgroup/systemd

See https://github.com/lathiat/avahi/blob/master/avahi-daemon/sd-daemon.c. The (buggy) code reads:

```
int sd_booted(void) {
#if defined(DISABLE_SYSTEMD) || !defined(__linux__)
        return 0;
#else

        struct stat a, b;

        /* We simply test whether the systemd cgroup hierarchy is
         * mounted */

        if (lstat("/sys/fs/cgroup", &a) < 0)
                return 0;

        if (lstat("/sys/fs/cgroup/systemd", &b) < 0)
                return 0;

        return a.st_dev != b.st_dev;
#endif
}
```

However, the second path does not exist on any recent systemd release. This due to the usage of cgroups2 without any legacy backup code. The sd_booted from (recent?) systemd versions does a different check, see https://www.freedesktop.org/software/systemd/man/sd_booted.html:
> Internally, this function checks whether the directory /run/systemd/system/ exists. A simple check like this can also be implemented trivially in shell or any other language.

It seems currently the sd_booted function can be found at:
https://github.com/systemd/systemd/blob/master/src/libsystemd/sd-daemon/sd-daemon.c#L622

Quoting that code:
```
_public_ int sd_booted(void) {
        /* We test whether the runtime unit file directory has been
         * created. This takes place in mount-setup.c, so is
         * guaranteed to happen very early during boot. */

        if (laccess("/run/systemd/system/", F_OK) >= 0)
                return true;

        if (errno == ENOENT)
                return false;

        return -errno;

````

Could you please adjust the sd_booted code according to the systemd code? It might be good to link against libsystemd. Suggest to perhaps also check if any other copied systemd function is outdated.

**Comment by evverx** [comment]
I'll revert that PR shortly.
