### ISSUE TITLE
avahi-0.8.tar.gz release tarball missing build-db

### ISSUE THREAD

**Issue by Mad-Mason** [lathiat/avahi#298]
Hi

I've downloaded the tarball and tried to build on Slackware.
Running `./configure  --disable-mono --disable-monodoc` works OK but `make` fails with

make[2]: Entering directory '/usr/src/apple/avahi-0.8/service-type-database'
make[2]: *** No rule to make target 'build-db', needed by 'all-am'.  Stop.

With some head scratching, Googling and (finally) viewing of the code tree it seems that `build-db` is missing from the tarball (you may have gathered I'm not a C coder ;-) ).

I manually downloaded it and `make` is working now.

I hope this is a quick fix to the tarball and doesn't cause you to much trouble.

Thanks
Iain

**Comment by evverx** [comment]
It was addressed in https://github.com/lathiat/avahi/pull/281. Closing.
