### ISSUE TITLE
Reverse resolve TXT records of incoming connections

### ISSUE THREAD

**Issue by albertvaka** [lathiat/avahi#299]
Is there any mechanism in Avahi so I can query information from an incoming connection to my service? Imagine a network where two devices expose `MyService` and both include a TXT record with a `name` field. Device A sees Device B, queries its `name` and connects to it. Is there any way for Device B to know the `name` of the incoming connection from Device A? 

I've tried searching for the IP of the incoming connection (from Device A) in all the `MyService` services discovered by Device B, but usually this doesn't work because I end up comparing IPs against local DNS names or local DNS names in different formats, so I never get a match. Am I going in the right direction, though?

**Comment by evverx** [comment]
> I've tried searching for the IP of the incoming connection (from Device A) in all the MyService services discovered by Device B, but usually this doesn't work because I end up comparing IPs against local DNS names or local DNS names in different formats, so I never get a match

I think it should be possible to either use reverse lookups to get names and compare them or fully resolve services by resolving hostnames in their SRV record and compare IPs. Closing.
