### ISSUE TITLE
Fix usage of point 2 point devices

### ISSUE THREAD

**Issue by pacho2** [lathiat/avahi#30]
We got this downstream report some time ago:
https://bugs.gentoo.org/show_bug.cgi?id=528722

When activating avahi for point 2 point devices (tun/tap) the daemon uses the destination address instead the local device address.

To fix that, the user provided the following patch... then, it would be nice if it could be reviewed by upstream and accepted if it's really ok. Thanks a lot:
https://528722.bugs.gentoo.org/attachment.cgi?id=388928

**Comment by lathiat** [comment]
We applied a patch for this already, though this patch goes about it in a different way.

I'll check to ensure it's working as expected.

**Comment by pacho2** [comment]
Nice, thanks a lot for taking care :)
