### ISSUE TITLE
Logic for point-to-point on tunnels incorrectly requires IFF_MULTICAST

### ISSUE THREAD

**Issue by pprindeville** [lathiat/avahi#305]
In the case of a point-to-point tunnel, there's only a single recipient at the other end, and therefore the distinction of unicast/multicast/broadcast is moot.

Requiring the `IFF_MULTICAST` flag is therefore meaningless in the present of `IFF_POINTOPOINT`.

**Comment by evverx** [comment]
I think it can be closed.
