### ISSUE TITLE
Anybody report / know of any issue with Cisco Service Discovery Gateway ?

### ISSUE THREAD

**Issue by mocallins** [lathiat/avahi#313]
I'm sort of testing out the usability of mDns/Avahi, as its so much easier to think and remember computer names, than ip addresses.

I think  I've got it lll configured correctly, because i can use avahi-browse and see many computer names in my little home lab.
However its mostly unreliable with Avahi, i very occasionaly get it to actually resolve a name and be able to do just a simple ping, by name.

On the Raspberry Pi's i have on my network, it seems to work properly, i did no tweaking, that i remember , of /etc/nsswitch.conf, that i've run into with TinyCore systems, running in the virtual env.

Any ideas / help would be greatly appreciated.
I didn't find any reference searching the issue here about working with Cisco or any other routers

I did initially have a problem with the routing , but got that solved as i didn't have a complete proper configuration, in the routers.
I  can ping any devices, on any of the subnets, by address, but not by name with avahi.

**Comment by evverx** [comment]
It's hard to tell what the issue was back in 2020. If this issue is still relevant please open a new issue with configs, debug logs, packets and so on. If this issue was more of a question it can be asked on the mailing list: https://lists.freedesktop.org/mailman/listinfo/avahi.
