### ISSUE TITLE
Example code licenses

### ISSUE THREAD

**Issue by firthmj** [lathiat/avahi#323]
Hi,

Is the example code also only available under the LGPL license?

In particular the core-browse-services.c and core-publish-service.c examples

As these are aimed at embedded applications, it doesn't seem uncommon to want to include parts of those examples into projects that are not GPL/LGPL code.

Obviously if that was the case, they would have to be dynamically linking against libavahi-core and libavahi-common, but that is probably a relatively common situation

**Comment by TUT-jiayou** [comment]
me too

**Comment by pemensik** [comment]
LGPL allows you to link with proprietary code, which does not have public source code. I think the license is as liberal as it can be. I doubt small parts of examples need different license. What exactly you want to do, which LGPL does not allow?

**Comment by evverx** [comment]
I'm not sure why the license should be changed. I think it can be closed.

(If things like this are important it's usually better to contact actual lawyers first)
