### ISSUE TITLE
Best way to report a security issue? 

### ISSUE THREAD

**Issue by marcdacier** [lathiat/avahi#329]
Hi, I would like to report a security issue on the avahi code without publicly disclosing it in this forum.  I can't find a security policy associated with this project, telling me how to report it. Can someone offer a contact point with whom I could explain the problem?   I have already sent emails to lathiat@bur.st but got no feedback. I'm thus unsure if that address is valid/read. 

Thanks for any hint you might have to help me in getting this fixed.

Marc

**Comment by lathiat** [comment]
Hi Marc

Thanks for opening the issue. That email address is still active but I don’t always check it. I gave your email and will respond. 

Thanks for reaching out

Trent

**Comment by nkarstens** [comment]
@lathiat Just wanted to let you know that I sent details on another potential issue to that same email address.

**Comment by lathiat** [comment]
Got your email thanks @nkarstens have responded. For future reference best e-mail is trent@lloyd.id.au or security@avahi.org
