### ISSUE TITLE
unable to get avahi 0.8 running on raspbian buster

### ISSUE THREAD

**Issue by ddppddpp** [lathiat/avahi#336]
Can anybody please provide instructions how to get avahi 0.8 running on raspbian buster?
I had 0.7.x installed via the package manager and running but decided to move to 0.8 because of name conflicts in a reflector setup.
I can get 0.8 compiled and installed from source, however avahi-daemon exits upon the first invocation of avahi-browse.
I'd happily provide details to anybody who's willing to help.

**Comment by ddppddpp** [comment]
Additional info:
- building with `./configure --with-distro=none --disable-mono --disable-qt5`
- I then run the daemon in debug mode and upon `avahi-browse -a` I get he following error:
```
dbus-protocol.c: interface=org.freedesktop.Avahi.Server, path=/, member=GetAPIVersion
dbus-protocol.c: interface=org.freedesktop.Avahi.Server, path=/, member=GetState
dbus-protocol.c: interface=org.freedesktop.Avahi.Server, path=/, member=ServiceTypeBrowserNew
avahi-daemon: running [myhostname.local]: symbol lookup error: avahi-daemon: running [myhostname.local]: undefined symbol: avahi_s_service_type_browser_prepare
```

**Comment by thefiredragon** [comment]
Same here under LXC arm64 privileged.

**Comment by evverx** [comment]
> undefined symbol: avahi_s_service_type_browser_prepare

This error message indicates that `avahi` wasn't installed correctly in the sense that the newer locally built avahi daemon was linked against the older shared library provided by the distribution. Both `avahi-daemon` and the `libavahi-core` shared library should be in sync for it to work and how to install it properly depends on the distribution. I think the most reliable way to get avahi to work there would be to use the package (or the exact configure/make arguments) provided by the distribution to install avahi. I think this issue can be closed.
