### ISSUE TITLE
 avahi does not run ipv4 at 169.254.x.x/16 (debian, ubuntu, oracle linux 7 and 8 and opensuse 15)

### ISSUE THREAD

**Issue by brunosoouza** [lathiat/avahi#339]
in all linux distro that install avahi (avahi + avahi-autoipd) the ipv4 address does not work at all, searching the internet I found a tip in the file / etc / sysconfig / network and mark NOZERCONF = no this corrected the problem of getting printing error every time in the terminal, but ipv4 does not run and I have already enabled it in the settings of the file / etc / avahi / avahi-daemon, I can only use ipv4 when I run avahi-autoipd in my hand inside the terminal, if I put this command in systemd it goes up ipv4 for less than a minute, is there any official doc on how to solve this problem? many tutorials claim to be easy to use but every distro I try I see that the thing is not so easy
I had this problem in the following distros: debian, ubuntu, oracle linux 7 and 8 and opensuse 15

**Comment by evverx** [comment]
My guess would be that it's caused by https://github.com/lathiat/avahi/issues/345
