### ISSUE TITLE
Syscall param ioctl(SIOCGIFINDEX) points to uninitialised byte(s) in GetNetworkInterfaceIndexByName

### ISSUE THREAD

**Issue by mikispag** [lathiat/avahi#34]
Issuing two dbus method calls of `GetNetworkInterfaceIndexByName`, first with a short string and then with a long one, makes avahi-daemon point to uninitialised bytes when calling `ioctl(SIOCGIFINDEX)`, according to valgrind.

```
DEBUG:root:TEST #1201: org.freedesktop.Avahi / org.freedesktop.Avahi.Server->GetNetworkInterfaceIndexByName with (('en0',),)
DEBUG:root:TEST #1202: org.freedesktop.Avahi / org.freedesktop.Avahi.Server->GetNetworkInterfaceIndexByName with (('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',),)
```

```
==7836== Syscall param ioctl(SIOCGIFINDEX) points to uninitialised byte(s)
==7836==    at 0x6206337: ioctl (syscall-template.S:81)
==7836==    by 0x6228076: if_nametoindex (if_index.c:48)
==7836==    by 0x40EAE0: msg_server_impl (dbus-protocol.c:376)
==7836==    by 0x5ACBE95: ??? (in /lib/x86_64-linux-gnu/libdbus-1.so.3.7.6)
==7836==    by 0x5ABEA20: dbus_connection_dispatch (in /lib/x86_64-linux-gnu/libdbus-1.so.3.7.6)
==7836==    by 0x414B35: dispatch_timeout_callback (dbus-watch-glue.c:105)
==7836==    by 0x4E3E647: avahi_simple_poll_dispatch (in /usr/lib/x86_64-linux-gnu/libavahi-common.so.3.5.3)
==7836==    by 0x406FD9: main (main.c:1256)
==7836==  Address 0xfff0004b0 is on thread 1's stack
==7836==  Uninitialised value was created by a stack allocation
==7836==    at 0x405D60: ??? (in /tmp/avahi-daemon-noasan)
```

**Comment by lathiat** [comment]
This seems strange; I find it curious the current code as an #ifdef VALGRIND_WORKAROUND in this exact area but was done a very long time ago!

The only parameter sent to the ioctl is the interface name, which is returned (and allocated) by dbus_message_get_args

Looking at the glibc if_nametoindex code in glibc, it copies from this buffer into the request buffer using strncpy with sizeof (ifr.ifr_name) which has size IF_NAMESIZE (=16)
From [glibc/sysdeps/unix/sysv/linux/if_index.c](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/if_index.c;h=8ba5eae7818b49cd77d94049696b3d569de82fe9;hb=HEAD#l34)
`   strncpy (ifr.ifr_name, ifname, sizeof (ifr.ifr_name));`

From [strcpy(3)](https://linux.die.net/man/3/strcpy): 
> The strncpy() function is similar, except that at most n bytes of src are copied.  Warning: If there is no null byte among the  first  n  bytes  of  src,  the string placed in dest will not be null-terminated.

Testing it's definitely the size of this string being >= 16 that is triggering the valgrind error (the smaller than larger size is not required).  I haven't tried to use valgrind with gdb much so was struggling to figure out exactly what access is uninitialised as I assumed that ioctl would just be sending this entire struct and not trying to read it in any string-like fashion so I'll need to look into that further to understand what's happening.

In any case we possibly should limit the interface name size being passed into the call in any case to IF_NAMESIZE

**Comment by evverx** [comment]
Given that `valgrind` no longer complains about that I think it is a false positive. My guess would be that `ioctl(SIOCGIFINDEX)` wasn't instrumented back in the day and `VALGRIND_WORKAROUND` was most likely supposed to get it around by avoiding calling that `ioctl` indirectly via `if_nametoindex` and `if_indextoname`. `VALGRIND_WORKAROUND` can safely be removed and I'll try to send a PR soon.

> In any case we possibly should limit the interface name size being passed into the call in any case to IF_NAMESIZE

`if_nametoindex` started rejecting names like that back in 2017 in https://sourceware.org/git/?p=glibc.git;a=commit;f=sysdeps/unix/sysv/linux/if_index.c;h=2180fee114b778515b3f560e5ff1e795282e60b0 to fix https://sourceware.org/bugzilla/show_bug.cgi?id=22442.

All in all I think this issue can be closed.

@mikispag just out of curiosity I wonder if those strings were generated by `dfuzzer`: https://github.com/dbus-fuzzer/dfuzzer?
