### ISSUE TITLE
avahi-daemon stops in multi-user.target

### ISSUE THREAD

**Issue by everdrone** [lathiat/avahi#343]
When running in `graphical.target`, avahi-daemon works perfectly.

But after switching the default target with
```
systemctl set-default multi-user.target
```

Avahi-daemon stops. this is a `journalctl` excerpt:
```
avahi[4204]: Avahi detected that your currently configured local DNS server serves
avahi[4204]: a domain .local. This is inherently incompatible with Avahi and thus
avahi[4204]: Avahi stopped itself. If you want to use Avahi in this network, please
avahi[4204]: contact your administrator and convince him to use a different DNS domain,
avahi[4204]: since .local should be used exclusively for Zeroconf technology.
avahi[4204]: For more information, see http://avahi.org/wiki/AvahiAndUnicastDotLocal
```

---

If anyone is having the same problem, the workaround is to set `AVAHI_DAEMON_DETECT_LOCAL=0` in `/etc/default/avahi-daemon`

But why is `graphical.target` required to have avahi-daemon working?
How can I see what's missing in `multi-user.target` that causes avahi to stop?

I'm using version `0.7-3.1ubuntu1.2 arm64`  
The config is unchanged.  

Here's nsswitch.conf:
```
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat systemd
group:          compat systemd
shadow:         compat
gshadow:        files

hosts:          files mdns4_minimal [NOTFOUND=return] dns myhostname
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis
```

**Comment by pemensik** [comment]
What is your content of */etc/resolv.conf*? what does return command ``dig local soa`` on your host?

**Comment by evverx** [comment]
That log message wasn't produced by Avahi. It was produced by a distro-specific script. Closing.

if it's still relevant it should be brought up downstream somewhere but as far as I can see at least Debian removed it in https://salsa.debian.org/utopia-team/avahi/-/commit/ac54649321cd5917d9611f4ff6dd848021ac357b
