### ISSUE TITLE
`avahi-daemon` does not play nice with `radvd` `AdvDefaultLifetime 0;` advertisements

### ISSUE THREAD

**Issue by ShadowJonathan** [lathiat/avahi#346]
I'm currently trying to install a non-default Yggdrasil gateway on my network, this means that it provides a `300::/64` prefix and can route to `200::/7`.

`radvd` has the following config, as suggested by the site;

```
interface eth0
{
     AdvSendAdvert on;
     AdvDefaultLifetime 0;

     prefix 300:1234:dead:beef::/64 {
         AdvOnLink on;
         AdvAutonomous on;
     };
     route 200::/8 {};
};
```

(`1234:dead:beef` being some bogus data for this issue filing)

When started, all of my devices on my local network play nice (the right `ip route` gets registered, the right ip addresses get registered). However, only my pc (which uses `avahi-daemon`) does not play nice, IP addresses get picked up, but the route is not added (only `300:1234:dead:beef::/64 dev br0`, with `br0` being my kvm bridge interface to my actual ethernet interface)

Removing `AdvDefaultLifetime 0;` from the config adds another "default route", which I think i don't want.

Version: `0.8`

**Comment by ShadowJonathan** [comment]
(I should mention that radvd is on a different computer, not the same as the avahi-daemon)

**Comment by evverx** [comment]
avahi doesn't receive router advertisements. Looks like whatever receivied RAs at the time didn't take zero lifetimes into account or something like that and the issue could probably have been observed without avahi running on the host. If it happens only when avahi is run let me know and I'll reopen the issue.
