### ISSUE TITLE
Host name conflict (again)

### ISSUE THREAD

**Issue by rrobinet** [lathiat/avahi#355]
1. Environment
========
2x Raspberry pi (P2 and P4)

2. Version
=====
Model		: Raspberry Pi 2 Model B Rev 1.1
Linux HomePiNasServer 5.10.52-v7+ #1441 SMP Tue Aug 3 18:10:09 BST 2021 armv7l GNU/Linux
avahi-daemon 0.7
Model		: Raspberry Pi 4 Model B Rev 1.2
Linux HomePiServer 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l GNU/Linux
avahi-daemon 0.7

3. DHCP Configuration
============
**Pi 4**
```
interface eth0
static ip_address=192.168.0.10/24
static ip6_address=fd51:42f8:caae:d92e::ff/64
static routers=192.168.0.1
static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1
```
**Pi 2**
```
interface eth0
static ip_address=192.168.0.252/24
static ip6_address=fd51:42f8:caae:d92e::ff/64
static routers=192.168.0.1
static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1
```

4. Avahi-daemon status
=============
**Pi 4**
```
sudo systemctl status avahi-daemon
● avahi-daemon.service - Avahi mDNS/DNS-SD Stack
   Loaded: loaded (/lib/systemd/system/avahi-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-08-23 17:24:37 CEST; 14h ago
 Main PID: 354 (avahi-daemon)
   Status: "avahi-daemon 0.7 starting up."
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/avahi-daemon.service
           ├─354 avahi-daemon: running [HomePiServer.local]
           └─378 avahi-daemon: chroot helper

Aug 23 17:25:00 HomePiServer avahi-daemon[354]: Registering new address record for 169.254.22.161 on vetha35871e.IPv4.
Aug 23 17:25:00 HomePiServer avahi-daemon[354]: Joining mDNS multicast group on interface veth5ee7a3c.IPv4 with address 169.254.48.19.
Aug 23 17:25:00 HomePiServer avahi-daemon[354]: New relevant interface veth5ee7a3c.IPv4 for mDNS.
Aug 23 17:25:00 HomePiServer avahi-daemon[354]: Registering new address record for 169.254.48.19 on veth5ee7a3c.IPv4.
Aug 23 17:25:00 HomePiServer avahi-daemon[354]: Joining mDNS multicast group on interface vethae2824c.IPv4 with address 169.254.9.87.
Aug 23 17:25:00 HomePiServer avahi-daemon[354]: New relevant interface vethae2824c.IPv4 for mDNS.
Aug 23 17:25:00 HomePiServer avahi-daemon[354]: Registering new address record for 169.254.9.87 on vethae2824c.IPv4.
Aug 23 17:25:01 HomePiServer avahi-daemon[354]: Joining mDNS multicast group on interface veth2fd5bb5.IPv4 with address 169.254.90.150.
Aug 23 17:25:01 HomePiServer avahi-daemon[354]: New relevant interface veth2fd5bb5.IPv4 for mDNS.
Aug 23 17:25:01 HomePiServer avahi-daemon[354]: Registering new address record for 169.254.90.150 on veth2fd5bb5.IPv4.
```
**Pi 2**
```
sudo systemctl status avahi-daemon
● avahi-daemon.service - Avahi mDNS/DNS-SD Stack
   Loaded: loaded (/lib/systemd/system/avahi-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-08-24 08:09:24 CEST; 19min ago
 Main PID: 518 (avahi-daemon)
   Status: "avahi-daemon 0.7 starting up."
    Tasks: 2 (limit: 2059)
   CGroup: /system.slice/avahi-daemon.service
           ├─518 avahi-daemon: registering [HomePiNasServer-86.local]
           └─519 avahi-daemon: chroot helper

Aug 24 08:28:39 HomePiNasServer avahi-daemon[518]: Host name conflict, retrying with HomePiNasServer-85
Aug 24 08:28:39 HomePiNasServer avahi-daemon[518]: Registering new address record for fd51:42f8:caae:d92e::ff on eth0.*.
Aug 24 08:28:39 HomePiNasServer avahi-daemon[518]: Registering new address record for 2a02:1811:437:e700:b472:4541:13e7:44ee on eth0.*.
Aug 24 08:28:39 HomePiNasServer avahi-daemon[518]: Registering new address record for 192.168.0.252 on eth0.IPv4.
Aug 24 08:28:59 HomePiNasServer avahi-daemon[518]: Withdrawing address record for 2a02:1811:437:e700:b472:4541:13e7:44ee on eth0.
Aug 24 08:28:59 HomePiNasServer avahi-daemon[518]: Withdrawing address record for 192.168.0.252 on eth0.
Aug 24 08:28:59 HomePiNasServer avahi-daemon[518]: Host name conflict, retrying with HomePiNasServer-86
Aug 24 08:28:59 HomePiNasServer avahi-daemon[518]: Registering new address record for fd51:42f8:caae:d92e::ff on eth0.*.
Aug 24 08:28:59 HomePiNasServer avahi-daemon[518]: Registering new address record for 2a02:1811:437:e700:b472:4541:13e7:44ee on eth0.*.
Aug 24 08:28:59 HomePiNasServer avahi-daemon[518]: Registering new address record for 192.168.0.252 on eth0.IPv4.
```
5. Syslog
====
**Pi 2**
```
tail -20 /var/log/syslog | grep avahi-daemon
Aug 24 08:29:19 HomePiNasServer avahi-daemon[518]: Registering new address record for 192.168.0.252 on eth0.IPv4.
Aug 24 08:29:39 HomePiNasServer avahi-daemon[518]: Withdrawing address record for 2a02:1811:437:e700:b472:4541:13e7:44ee on eth0.
Aug 24 08:29:39 HomePiNasServer avahi-daemon[518]: Withdrawing address record for 192.168.0.252 on eth0.
Aug 24 08:29:39 HomePiNasServer avahi-daemon[518]: Host name conflict, retrying with HomePiNasServer-88
Aug 24 08:29:39 HomePiNasServer avahi-daemon[518]: Registering new address record for fd51:42f8:caae:d92e::ff on eth0.*.
Aug 24 08:29:39 HomePiNasServer avahi-daemon[518]: Registering new address record for 2a02:1811:437:e700:b472:4541:13e7:44ee on eth0.*.
Aug 24 08:29:39 HomePiNasServer avahi-daemon[518]: Registering new address record for 192.168.0.252 on eth0.IPv4.
Aug 24 08:29:59 HomePiNasServer avahi-daemon[518]: Withdrawing address record for 2a02:1811:437:e700:b472:4541:13e7:44ee on eth0.
Aug 24 08:29:59 HomePiNasServer avahi-daemon[518]: Withdrawing address record for 192.168.0.252 on eth0.
Aug 24 08:29:59 HomePiNasServer avahi-daemon[518]: Host name conflict, retrying with HomePiNasServer-89
Aug 24 08:29:59 HomePiNasServer avahi-daemon[518]: Registering new address record for fd51:42f8:caae:d92e::ff on eth0.*.
Aug 24 08:29:59 HomePiNasServer avahi-daemon[518]: Registering new address record for 2a02:1811:437:e700:b472:4541:13e7:44ee on eth0.*.
Aug 24 08:29:59 HomePiNasServer avahi-daemon[518]: Registering new address record for 192.168.0.252 on eth0.IPv4.
Aug 24 08:30:19 HomePiNasServer avahi-daemon[518]: Withdrawing address record for 2a02:1811:437:e700:b472:4541:13e7:44ee on eth0.
Aug 24 08:30:19 HomePiNasServer avahi-daemon[518]: Withdrawing address record for 192.168.0.252 on eth0.
Aug 24 08:30:19 HomePiNasServer avahi-daemon[518]: Host name conflict, retrying with HomePiNasServer-90
Aug 24 08:30:19 HomePiNasServer avahi-daemon[518]: Registering new address record for fd51:42f8:caae:d92e::ff on eth0.*.
Aug 24 08:30:19 HomePiNasServer avahi-daemon[518]: Registering new address record for 2a02:1811:437:e700:b472:4541:13e7:44ee on eth0.*.
Aug 24 08:30:19 HomePiNasServer avahi-daemon[518]: Registering new address record for 192.168.0.252 on eth0.IPv4.
```
6. Issues
====
- avahi daemon unable to broadcast Pi 2 hostname (HomePiNasServer) if started after Pi 4 (HomePiServer).
 or 
- avahi daemon unable to broadcast Pi 4 hostname (HomePiServer) if started after Pi 4 (HomePiNasServer).
- Can't access server by name   (e.g ping HomePiNasServer.local)
- System log is abnormally filled with avahi-daemon logs
- Network is flooded with mDNS messages (see trace mDNS.txtZip)
- Note: that is a conflict only between raspberry, other mDNS devices are still working
7. Conditions
====== 

- DHCP configured with eth0 static address (no problem with dynamic address !!!!!)
- At least 2 raspberry connected on the same LAN network (no problem with only one !!!!)
- Changing the domain name of one raspberry doesn't help
- Changing the host name of one raspberry doesn't help
- Only IPV4 doesn't help

8. Current Solution
==========
Couldn't find any valid solution from previous submitted issues so if static IP address is necessary: 
- Use reserved dynamic IP address in DHCP server (if possible)
- Get rid of mDNS (apt purge avahi-daemon) and use static host file configuration in various systems
- Use official DNS registration (:-)
9. Network traces
=========
[mDNS.txt.zip](https://github.com/lathiat/avahi/files/7037057/mDNS.txt.zip)

**Comment by sergvpurik** [comment]
Is this correct that Pi 4 and Pi 2 have the same ip6_address?
```
static ip6_address=fd51:42f8:caae:d92e::ff/64
```

**Comment by rrobinet** [comment]
@sergvpurik 
You may have a point here ; I didn't payed attention to the IPV6 address, I don't know why there are the same, so I  have to check that again. 
Thanks for your feedback, I will verify  and comment.

**Comment by mvduin** [comment]
Interesting, so it's probably actually getting a conflict in the PTR record for the IPv6 address, which is part of the host's record set so it's incorrectly reporting it as a hostname conflict and fruitlessly trying to resolve it by changing the hostname (which obviously doesn't help).

The root problem here of course is the erroneous network configuration with conflicting static IPv6 addresses. It would be nice if avahi handled this scenario a bit more graceful although I think that would be difficult with its current internal structure, since the internal callback that reports the collision does not include any information about which record(s) collided.

BTW, while static address configuration still has some uses with IPv4, with IPv6 it is almost always a mistake. There's really no need to do that and the main thing it accomplishes is to decrease the probability that your network will work correctly. Leaving IPv6 auto-configured ensures all devices agree on the prefix(es) to be used and avoids address conflicts within these prefixes.

Prefixes are normally chosen and announced by IPv6 routers on your network, if any. If no prefix is being announced that's usually no problem either since all devices will still have a link-local address (prefix `fe80::/64`) they can use to communicate. The only reason I can think of to manually configure a unique-local prefix (like `fd51:42f8:caae:d92e::/64` in your current configuration) is to enable IPv6 communication in the absence of an IPv6 router for applications whose support for link-local IPv6 addresses is broken, e.g. Google Chrome. In that case, configure one or more devices to use _and announce_ this prefix, without statically configuring an address within that prefix, e.g. when using systemd-networkd:
```ini
[Network]
# systemd v247 or newer:
#IPv6SendRA=yes
# older versions of systemd (still supported by later versions for backwards compatibility):
IPv6PrefixDelegation=static

[IPv6Prefix]
Prefix=fd51:42f8:caae:d92e::/64

[IPv6SendRA]
# we're not actually a router but just announcing the prefix
RouterLifetimeSec=0
EmitDNS=false
EmitDomains=false
```

**Comment by mvduin** [comment]
(this is vaguely related to #117 but only in the sense of this being an unusual corner case that triggers spurious hostname renames)

**Comment by rrobinet** [comment]
@mvduin , @sergvpurik 
 Sorry to be so late but you are correct, the reason sounds stupid once you know it ...
In the DHCP template  (/etc/dhcpcd.conf) the example is:
# Example static IP configuration:
#interface eth0
#static ip_address=192.168.0.10/24
#static ip6_address=fd51:42f8:caae:d92e::ff/64
#static routers=192.168.0.1
#static domain_name_servers=192.168.0.1 8.8.8.8 fd51:42f8:caae:d92e::1

In my case I did use this template on several systems by removing the # sign and changing only the IPV4 address to  the one I want to use (unfortunately activating the default IPV6 one as well, which is of course the same for all my systems).
So the clash is well on the IPV6 one and not on the IPV4.
So the solution is quite simple, don't un-comment the IPV6 one or remove or use an actual one. 

Thanks to all of you expecting this issue will help others doing the same mistake as I did.
Robert
