### ISSUE TITLE
Diffrent domains on different interfaces

### ISSUE THREAD

**Issue by beremour** [lathiat/avahi#362]
Dear, Avahi
How to answer **hostname.domain1.local** on interface **eth1** and **hostname.domain2.local** on interface **eth2** ?

**Comment by pemensik** [comment]
I think hostnames on *.local* domain have to have only 2 labels. That means just single dot. Unless you want to use unicast DNS instead, which I would discourage with *.local* domain anyway.

**Comment by evverx** [comment]
It isn't supported. That being said if something like https://github.com/lathiat/avahi/issues/213 was implemented it would probably be possible to run two separate instances of avahi on one machine with two different configs allowing different interfaces. They would look like
```
[server]
allow-interfaces=eth1
domain-name=domain1.local
enable-dbus=no
```
and
```
[server]
allow-interfaces=eth2
domain-name=domain2.local
enable-dbus=no
```

**Comment by evverx** [comment]
>  .local domain have to have only 2 labels

avahi supports all kinds of domain names. I'm not sure why RH thinks that only `.local` is possible: https://github.com/lathiat/avahi/issues/155. Whether domain names like that should be used is another question.
