### ISSUE TITLE
Is there a way to keep PTR, TXT and SRV in the same standard query response?

### ISSUE THREAD

**Issue by kabassanov** [lathiat/avahi#364]
Hello,

My question could appear a little bit strange, but I'm looking for a way to keep PTR, SRV and TXT records in the same mdns network packet. The reason is that I have some issues with a third-party hardware implementing a kind of mdns proxy that ignores incoming PTR entries if related SRV and TXT records are not present in the same packet. And I have no way to obtain any update for it.

I saw in the TODO file that some work had been done to "add SRV and TXT records referenced from PTR records automatically to packet", but how could we keep them together with a kind of atomicity.

Any help will be appreciated.

Thanks.

**Comment by evverx** [comment]
avahi includes those RRs into packets (with `avahi_server_enumerate_aux_records`):
```sh
    3  43.028555 192.168.107.149 → 224.0.0.251  MDNS 75 Standard query 0x0000 PTR _ssh._tcp.local, "QM" question
    4  43.054924 192.168.107.145 → 224.0.0.251  MDNS 164 Standard query response 0x0000 PTR H._ssh._tcp.local TXT, cache flush SRV, cache flush 0 0 22 H.local AAAA, cache flush fe80::741a:afff:fe88:1910 A, cache flush 192.168.107.145
```
I'm not sure what the issue was.

**Comment by kabassanov** [comment]
The question vas related to a buggy equipment that drops RR packets if a PTR and its related TXT and SRV records are not included in the same packet, for instance if they follow in the next one due to a lack of place in the actual packet. So I was looking for a way to keep them grouped. Finally I did the code modification by myself. When the packet is going to be filled, if there is not enough place for all them, I just stop writing in the packet, and keep the PTR for the next one.

**Comment by evverx** [comment]
> When the packet is going to be filled, if there is not enough place for all them, I just stop writing in the packet, and keep the PTR for the next one

As far as I understand it doesn't help if PTR, TXT and SRV records combined can't fit into a single packet. Either way if it's still relevant it would be great if you could show the patch you apply to get past that mDNS proxy. It should make it easier to figure out where those services come from but I'm not sure it can be fixed in general on the avahi side.
