### ISSUE TITLE
static hosts only configuration doesn't work if all interfaces are in deny-interfaces

### ISSUE THREAD

**Issue by aguadoenzo** [lathiat/avahi#368]
I am trying to setup avahi on host A so that it only acts as a reflector for another host B. It shouldn't advertise for host A.
To achieve this, I add all network interfaces of host A in `deny-interfaces` and add the IP address of host B to `/etc/avahi/hosts`.

**What I expect**
Avahi should publish the hosts defined in `/etc/avahi/hosts` even with all interfaces of host A in `deny-interfaces`

**What happens**
Avahi doesn't publish any record. I've used `dns-sd` and the [Discovery](https://apps.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12) app to check for this. Removing all interfaces from `deny-interfaces` makes all records appear again in those tools.  
The issue is that an IP address from host A is also published, which is incorrect, only host B IP address should be published.

avahi-daemon v0.8

**Comment by evverx** [comment]
> It shouldn't advertise for host A

`publish-addresses=no` on host A should do the trick.
