### ISSUE TITLE
 [PATCH] avahi-core: Fix documentation of publish_aaaa_on_ipv4 in AvahiServerConfig struct

### ISSUE THREAD

**Issue by pmeerw** [lathiat/avahi#37]
avahi-core/core.h:
-    int publish_aaaa_on_ipv4;         /**< Publish an IPv4 A RR on IPv6 sockets */
-    int publish_aaaa_on_ipv4;         /**< Publish an IPv6 AAAA RR on IPv4 sockets */

see patch on mail list, thanks

**Comment by evverx** [comment]
It was included in 9b1c0d5b4a8e1f2b11cef62630e7e9dddcb7cb99 as far as I can see.
