### ISSUE TITLE
avahi keeps trying and failing to register new address when publishing is disabled

### ISSUE THREAD

**Issue by JamesCrompton** [lathiat/avahi#38]
I have a machine with publishing disabled (avahi-daemon.conf attached) and every two minutes the system log has a set of entries like this:

Nov 29 12:53:53 x avahi-daemon[413]: Registering new address record for fe80::c68e:8fff:fef5:d20f on wlan0.*.
Nov 29 12:53:53 x avahi-daemon[413]: iface.c: avahi_server_add_address() failed: Not permitted
Nov 29 12:53:53 x avahi-daemon[413]: Registering new address record for 192.168.123.5 on wlan0.IPv4.
Nov 29 12:53:53 x avahi-daemon[413]: iface.c: avahi_server_add_address() failed: Not permitted

Indeed, most of the system log consists of notifications that avahi is trying and failing to do something it has been told not to do.

[avahi-daemon.conf.txt](https://github.com/lathiat/avahi/files/46579/avahi-daemon.conf.txt)

**Comment by donfranio** [comment]
Same here, when I set
```
disable-publishing=yes
```
I also get those errors in syslog. Setting it to ```no``` makes them vanish.

**Comment by dkerr64** [comment]
I have included  fix for this (simply suppressing the warning message) in my pull request #62 so if that every gets merged this will be fixed

**Comment by evverx** [comment]
As far as I can tell it was addressed in 2e42c6416327c256ab70940c7341caf3830d5c24. Closing.
