### ISSUE TITLE
Interface removal while group announcements probing leaves group hanging 

### ISSUE THREAD

**Issue by awy** [lathiat/avahi#383]
When `remove_announce()` is called, perhaps because an interface is no longer relevant, and the announcer was probing, then the associated group's `n_pending` count is not decremented and so remaining announcers in the group will never move to ` AVAHI_ANNOUNCING`.

**Comment by evverx** [comment]
As far as I understand it was presumably fixed in https://github.com/lathiat/avahi/pull/39. I think this issue can be closed.
