### ISSUE TITLE
can not set host name in client-publish-service.c

### ISSUE THREAD

**Issue by WangFengtu1996** [lathiat/avahi#385]
Hello,all

I try to modify the server host name, in the c language demo`client-publish-service.c`. But the error `Failed to add _ipp._tcp service: Invalid host name` is got. I also try other host name, the same error is got. When I did not modified the source code, the service is published and browsed rightly. 

# env
* ubuntu 18
* c language
* configure command 
```
./autogen.sh   --disable-qt5  --disable-gtk3  --disable-gdbm  --disable-python  --disable-manpages --disable-mono --enable-tests 
make
```

# modified source code `client-publish-service.c`

```
        if ((ret = avahi_entry_group_add_service(group, AVAHI_IF_UNSPEC, AVAHI_PROTO_INET, 0, name, "_osware._tcp", NULL, "xxghaldaljfagalghalhgalg", 8888, "test=blah","Day=4","Month=7","Year=2022", r, NULL)) < 0) {

            if (ret == AVAHI_ERR_COLLISION)
                goto collision;

            fprintf(stderr, "Failed to add _ipp._tcp service: %s\n", avahi_strerror(ret));
            goto fail;
        }
```

Thanks for your time. If other infos are needed, please tell me.

**Comment by evverx** [comment]
avahi expects that argument to be an FQDN. It should be possible to get it to work by appending `.local` to `xxghaldaljfagalghalhgalg`.
