### ISSUE TITLE
README reference to IRC is out-of-date

### ISSUE THREAD

**Issue by pprindeville** [lathiat/avahi#399]
The `README` refers to:

```
IRC:
	#avahi on irc.freenode.org
```

but `freenode.org` for all intents and purposes no longer exists.

**Comment by pemensik** [comment]
Even ``#avahi`` channel on libera.chat does not exist. Do we want or need it?

**Comment by pemensik** [comment]
Created ``#avahi`` channel on libera.chat, if anyone wants to join.
