### ISSUE TITLE
serious memory leak found in avahi-daemon

### ISSUE THREAD

**Issue by believe209** [lathiat/avahi#400]
when we do some DNS-SD test with avahi-daemon, we found it has abnormal memory footprint. 
**The memory usage is increasing significantly with our test going on. 
Finally, we found it use totally VmPeak: 109332 kB and VmRSS: 28056 kB**.
see below info.

$ cat /proc/3950888/status
Name:   avahi-daemon
Umask:  0022
State:  S (sleeping)
Tgid:   3950888
Ngid:   0
Pid:    3950888
PPid:   1
TracerPid:      0
Uid:    119     119     119     119
Gid:    128     128     128     128
FDSize: 256
Groups: 128
NStgid: 3950888
NSpid:  3950888
NSpgid: 3950888
NSsid:  3950888
VmPeak:   109332 kB
VmSize:   105440 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:     28452 kB
**VmRSS:     28056 kB**
RssAnon:           24432 kB
RssFile:            3624 kB
RssShmem:              0 kB
**VmData:    97432 kB**
VmStk:       132 kB
VmExe:        96 kB
VmLib:      3948 kB
VmPTE:       244 kB
VmSwap:        0 kB
HugetlbPages:          0 kB
CoreDumping:    0
THP_enabled:    1
Threads:        1
SigQ:   0/31354
SigPnd: 0000000000000000
ShdPnd: 0000000000000000
SigBlk: 0000000000000000
SigIgn: 0000000000001000
SigCgt: 0000000180004203
CapInh: 0000000000000000
CapPrm: 0000000000000000
CapEff: 0000000000000000
CapBnd: 0000003fffffffff
CapAmb: 0000000000000000
NoNewPrivs:     0
Seccomp:        0
Speculation_Store_Bypass:       thread vulnerable
Cpus_allowed:   ffffffff,ffffffff,ffffffff,ffffffff
Cpus_allowed_list:      0-127
Mems_allowed:   00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:      0
voluntary_ctxt_switches:        20469
nonvoluntary_ctxt_switches:     4467

The reproducible steps are very simple, just do the below command:
watch -n 10 avahi-browse-domains --domain=dns-sd.org -arpt

**Comment by believe209** [comment]
the avahi-daemon 0.6.31/0.7/0.8 version all has the same question.

**Comment by pemensik** [comment]
When I am running ``avahi-browse-domains --domain=dns-sd.org -arpt`` on my machine, it very often prints error: ``service_browser failed: Not found``. Found by adding additional log that it relates to *_http._tcp* type. Could those errors be a reason for unfreed memory? Do those errors happen to you too?

Would you please share output, what does above command print to you? Please use triple backticks to format the output.
This is printed on my machine. Amount of lines printed is random, it never prints the whole list successfully. Is that wrong network configuration on my side? Can avahi process successfuly *dns-sd.org* domain?

```
$ avahi-browse-domains --domain=dns-sd.org -arpt
+;n/a;n/a;stuart\226\128\153s\032remote\032airprint\032printer;_ipp._tcp;dns-sd.org
+;n/a;n/a;sales;_ipp._tcp;dns-sd.org
+;n/a;n/a;marketing;_ipp._tcp;dns-sd.org
+;n/a;n/a;engineering;_ipp._tcp;dns-sd.org
+;n/a;n/a;3rd\.\032floor\032copy\032room;_ipp._tcp;dns-sd.org
+;n/a;n/a;microsoft\032developer\032files;_ftp._tcp;dns-sd.org
+;n/a;n/a;apple\032quicktime\032files;_ftp._tcp;dns-sd.org
+;n/a;n/a;restricted\044\032registered\032users\032only;_ftp._tcp;dns-sd.org
+;n/a;n/a;3rd\.\032floor\032copy\032room;_pdl-datastream._tcp;dns-sd.org
+;n/a;n/a;engineering;_pdl-datastream._tcp;dns-sd.org
+;n/a;n/a;marketing;_pdl-datastream._tcp;dns-sd.org
+;n/a;n/a;sales;_pdl-datastream._tcp;dns-sd.org
+;n/a;n/a;linux\032server;_afpovertcp._tcp;dns-sd.org
+;n/a;n/a;stuart\226\128\153s\032cube;_afpovertcp._tcp;dns-sd.org
+;n/a;n/a;shared\032files;_afpovertcp._tcp;dns-sd.org
+;n/a;n/a;marketing;_printer._tcp;dns-sd.org
+;n/a;n/a;sales;_printer._tcp;dns-sd.org
+;n/a;n/a;3rd\.\032floor\032copy\032room;_printer._tcp;dns-sd.org
+;n/a;n/a;engineering;_printer._tcp;dns-sd.org
service_browser failed: Not found
```

**Comment by WeiLiCalix** [comment]
> When I am running `avahi-browse-domains --domain=dns-sd.org -arpt` on my machine, it very often prints error: `service_browser failed: Not found`. Found by adding additional log that it relates to __http._tcp_ type. Could those errors be a reason for unfreed memory? Do those errors happen to you too?
> 
> Would you please share output, what does above command print to you? Please use triple backticks to format the output. This is printed on my machine. Amount of lines printed is random, it never prints the whole list successfully. Is that wrong network configuration on my side? Can avahi process successfuly _dns-sd.org_ domain?
> 
> ```
> $ avahi-browse-domains --domain=dns-sd.org -arpt
> +;n/a;n/a;stuart\226\128\153s\032remote\032airprint\032printer;_ipp._tcp;dns-sd.org
> +;n/a;n/a;sales;_ipp._tcp;dns-sd.org
> +;n/a;n/a;marketing;_ipp._tcp;dns-sd.org
> +;n/a;n/a;engineering;_ipp._tcp;dns-sd.org
> +;n/a;n/a;3rd\.\032floor\032copy\032room;_ipp._tcp;dns-sd.org
> +;n/a;n/a;microsoft\032developer\032files;_ftp._tcp;dns-sd.org
> +;n/a;n/a;apple\032quicktime\032files;_ftp._tcp;dns-sd.org
> +;n/a;n/a;restricted\044\032registered\032users\032only;_ftp._tcp;dns-sd.org
> +;n/a;n/a;3rd\.\032floor\032copy\032room;_pdl-datastream._tcp;dns-sd.org
> +;n/a;n/a;engineering;_pdl-datastream._tcp;dns-sd.org
> +;n/a;n/a;marketing;_pdl-datastream._tcp;dns-sd.org
> +;n/a;n/a;sales;_pdl-datastream._tcp;dns-sd.org
> +;n/a;n/a;linux\032server;_afpovertcp._tcp;dns-sd.org
> +;n/a;n/a;stuart\226\128\153s\032cube;_afpovertcp._tcp;dns-sd.org
> +;n/a;n/a;shared\032files;_afpovertcp._tcp;dns-sd.org
> +;n/a;n/a;marketing;_printer._tcp;dns-sd.org
> +;n/a;n/a;sales;_printer._tcp;dns-sd.org
> +;n/a;n/a;3rd\.\032floor\032copy\032room;_printer._tcp;dns-sd.org
> +;n/a;n/a;engineering;_printer._tcp;dns-sd.org
> service_browser failed: Not found
> ```

I wonder if when you see "service_browser failed: Not found", the avahi-daemon is died.

**Comment by WeiLiCalix** [comment]
Here is the output at my openwrt router:

![image](https://user-images.githubusercontent.com/116779210/204411620-6161dd9c-8c19-49ca-a3d0-b23d381eff00.png)

**Comment by evverx** [comment]
As far as I understand https://github.com/lathiat/avahi/pull/434 was supposed to fix it. @WeiLiCalix assuming you've applied the patch can you confirm that the issue is gone and no side effects have been observed?

**Comment by evverx** [comment]
I think it should be safe to assume that no side effects have been observed. Closing.
