### ISSUE TITLE
avahi-autoipd's iface-linux.c uses IFLA_RTA instead of IFA_RTA, crashes some platforms

### ISSUE THREAD

**Issue by fastcat** [lathiat/avahi#42]
See this line of code: https://github.com/lathiat/avahi/blob/master/avahi-autoipd/iface-linux.c#L144

It's processing an ifaddrmsg, but using a macro for an ifinfomsg.  The sizes are different, and this means that it's at least getting the data wrong, and on an ARM platform I'm using, this makes avahi-autoipd crash.

**Comment by lathiat** [comment]
Thanks for picking this up and reporting it.  You are correct the wrong function is used and I will commit a fix for this.

Could you tell me which specific arm platform / kernel version this was failing on?

**Comment by fastcat** [comment]
This was found on a Broadcom ARM SoC, and on investigation was found to also affect (= cause a crash) a related Broadcom MIPS SoC, though at much lower frequency.  The ARM SoC that crashed on this nearly 100% was running a 3.14.28-derived kernel.
