### ISSUE TITLE
is there a plan for v0.9 tag?

### ISSUE THREAD

**Issue by ilkery** [lathiat/avahi#430]
Hi all,
 Do you have a plan for v0.9 tag for this repo?

**Comment by pemensik** [comment]
not yet, no plan or expected time for a new release is known. Current plan is to process all pending bug pull requests, but it might take some time.

**Comment by Neustradamus** [comment]
@pemensik: It will be nice to have a new version before Debian 12 freeze...

**Comment by Neustradamus** [comment]
For information:
- https://tracker.debian.org/pkg/avahi

**Comment by Neustradamus** [comment]
@lathiat: It is now too late for Debian 12, I think that the new version could be released after the migration to the new place.
Badly, we have lost a lot of months...
- https://github.com/avahi-project

**Comment by pemensik** [comment]
I think we should consolidate in current place and prepare release in this place. There is a lot of unsolved issues, which are waiting for review and merge. I think it works for now. Can you review pending pull requests and choose those ready to merge? I agree an organization would be better, but multiple people were given commit access. I would like to fix all issues with known resolution before the next release. Can you check all patches from Debian are merged here or are distribution specific changes only?

**Comment by Neustradamus** [comment]
@pemensik: Unsolved issues will be same with a transfer in an organization, repository move only the place without lost current links...

All people need to review...

**Comment by evverx** [comment]
I think this issue can be closed. The progress can be tracked at https://github.com/lathiat/avahi/milestone/4.

**Comment by Neustradamus** [comment]
Dear @evverx,

Can you reopen this ticket because there is no 0.9 version:
- https://github.com/lathiat/avahi/tags
- https://github.com/lathiat/avahi/releases

Thanks in advance.

**Comment by evverx** [comment]
> there is no 0.9 version

I'm aware of that.

> Can you reopen this ticket

I wonder why it should be reopened? The question was answered in https://github.com/lathiat/avahi/issues/430#issuecomment-1363419249
> not yet, no plan or expected time for a new release is known. Current plan is to process all pending bug pull requests, but it might take some time.

and the progress can be tracked at https://github.com/lathiat/avahi/milestone/4.

**Comment by Neustradamus** [comment]
After this closed ticket and the previous from me (https://github.com/lathiat/avahi/issues/325), I have done a ticket about all current CVEs since 2021, security is important, a new release is always requested:
- https://github.com/lathiat/avahi/issues/503

**Comment by pemensik** [comment]
Made [v0.9-rc](https://github.com/avahi/avahi/tree/v0.9-rc2) tag, which should be reasonable version for now. I would like to have no fixable vulnerabilities in the final release, but so far we have discovered more problems when fixing known ones. Sorry, it does not fix itself and I cannot be dedicated to avahi only.
