### ISSUE TITLE
Avahi sometimes bundles browsing responses for different browsers into one send()

### ISSUE THREAD

**Issue by zdohnal** [lathiat/avahi#442]
Hi,

I found out Avahi sometimes bundles several responses into one syscall (strace is available in downstream [issue](https://bugzilla.redhat.com/show_bug.cgi?id=1954469)), which causes problems for programs which runs Avahi API and wait for data from Avahi, which they process further. ```ippfind``` tool from CUPS is such program.

Since AFAIK Avahi response doesn't contain a reliable flag which we can look for to find out Avahi browsing is done, we wait till poll() which watches Avahi browser descriptor reports no data for reading - in case Avahi bundles the response, Avahi browsers are not able to process the incoming data in time.

Would you mind looking into the issue and fix the daemon, so it doesn't bundle responses?

**Comment by pemensik** [comment]
I would have to look into the code of avahi-browse myself, but it has -t or -c parameters to end browsing when everything from cache were printed. Is that the problem being reported? I think receiving multiple responses in single syscall is desirable and okay, I do not think the client software should rely on the number of calls.

**Comment by pemensik** [comment]
I think we need much better formulation what is the original problem solved by reliance on separate answers. It is not even clear to me which kind of API is used by *ippfind* and when it can request multiple *different browsers*. Which receives only one reply, which is not enough and why?

It seems to be starting a new browsing should not be necessary and would be even wrong if the previous one have not yet finished. I would expect those should have the same results. If they are different, we need to dig more into deeps why it is so. But I think one application should have only one browse active at one time. I have no expert on Avahi or MDNS yet, maybe I miss something obvious.

**Comment by zdohnal** [comment]
Explained in person.

To sum it up - we create separate browsers to have an answer quickly. Currently ippfind is used in driverless backend, which does generating PPDs and device uris. The driverless backend is run by cups-driverd and cups-deviced helper executables, which has a default small (about 15s) timeout, so we want to have the answer as fast we can.

The issue is Avahi doesn't seem to provide a reliable way of telling "I'm done" - event ALL_FOR_NOW seems unreliable even in mDNSResponder.

I've checked the DBUS communication vs strace output and I can verify that DBUS responses from avahi-daemon are separate, but bundled in one recvmsg() syscall - so the issue is triggered when glibc/kernel bundles the messages into one syscall, so Avahi is not to blame.

I'll check once again how reliable ALL_FOR_NOW event in Avahi is, and probably rewrite ippfind to use separate clients to avoid bundled behavior.
