### ISSUE TITLE
bssh: p field of TXT record for ssh password ignored

### ISSUE THREAD

**Issue by StephDC** [lathiat/avahi#443]
I am attempting to use `bssh` (avahi-ui/bssh.c) to login to a ssh service that publishes its username and password using the TXT record.

bssh correctly recognized the `u` field and used it as the user name, but the `p` field as defined in https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml seems to be ignored.

While I can definitely run an `avahi-browse -tr _ssh._tcp` to copy the password down, it is more of an inconvenience, especially to users who do not know so much about avahi.

Is it intentional or would it be considered as a feature that could be added?

**Comment by StephDC** [comment]
There is password to limit access from the Internet to those who knows the password. For those who have access to the L2 network which IMO is pretty close to having physical access to the device, to me the password is not so important and letting one know the password to do some work can help on the maintenance side of operation. Also securing a L2 network to me is less difficult than securing a L3 with IP routing and port etc., while securing it on L1 is less practical for I still want it to have access to the Internet.

Also as the p field is defined in IANA. Maybe if there is no such use case of announcing a u/p combination in Avahi, such field would not be defined there?

**Comment by evverx** [comment]
`bssh` can be dropped in the foreseeable future (at least it came up in https://github.com/lathiat/avahi/issues/516). Regardless of whether it stays or not new features are unlikely to be added so I'll go ahead and close it as not planned.

(If you don't think it should be dropped it would be great it you could comment there)
