### ISSUE TITLE
repeatedly append ".local" to query section PTR record when using avahi_entry_group_add_record()

### ISSUE THREAD

**Issue by hyh19962008** [lathiat/avahi#445]
Hi, I'm using the following code to add a record. Using Wireshark to capture the published packets. 
I can see correct PTR record in the answer section, whose name is "_services._dns-sd._udp.local" and domain name is "_ttap._udp.local". 
But in the query section, I got a PTR record with name "_ttap._udp.local.local", where ".local" is appended falsely.

```c
char service_name[] = "_ttap._udp.local";
char dns_sd_service_name[] = "_services._dns-sd._udp.local";

uint8_t rrlen;
int rr_size;
uint8_t *ptr_mem;

rrlen = strlen(service_name);
rr_size = rrlen + 2;                          // 1B size + 1B '\0'
ptr_mem = malloc(rr_size);
memcpy(ptr_mem, &rrlen, 1);
strcpy(ptr_mem+1, service_name);

avahi_entry_group_add_record(entry_group, AVAHI_IF_UNSPEC, AVAHI_PROTO_UNSPEC, 
        AVAHI_PUBLISH_ALLOW_MULTIPLE | AVAHI_PUBLISH_USE_MULTICAST,
        dns_sd_service_name, AVAHI_DNS_CLASS_IN, AVAHI_DNS_TYPE_PTR, 
        AVAHI_DEFAULT_TTL, ptr_mem, rr_size);
```

**Comment by hyh19962008** [comment]
problem was seen in 0.6.31, 0.7, 0.8

**Comment by evverx** [comment]
`avahi_entry_group_add_record` consumes raw labels so to add the three labels something like
```c
avahi_entry_group_add_record(..., "\5_ttap\4_udp\5local\0", 18);
```
should be passed to it instead. Without that `service_name` is treated as a single label and the resource records contain
```python
\x12\x10_ttap._udp.local\x00
```
