### ISSUE TITLE
Found signals from the service resolver are emitted before call to start on D-Bus

### ISSUE THREAD

**Issue by kapetan** [lathiat/avahi#446]
Hi,

I want to use the Avahi D-Bus API to resolve services. I'm using the newer `Server2` interface with `ServiceResolverPrepare` and then calling the `Start` method on the service resolver to start receiving `Found` signals. The issue I'm seeing is that I start receiving `Found` before calling the `Start` method on the service resolver. I also get the events without ever calling the `Start` method on the resolver. 

It seems to be enough to call the `Start` on the service browser instance for the resolvers also to begin emitting signals on the bus.

My understanding is that the `Found` and `Failure` signals on the resolver will not be emitted before calling `Start`. I've attached the logs from dbus-monitor where you can see the timing of the messages.

[avahi-dbus-monitor.log](https://github.com/lathiat/avahi/files/11159837/avahi-dbus-monitor.log): `Found` signals before call to `Start` on the service resolvers.
[avahi-dbus-monitor_no-start.log](https://github.com/lathiat/avahi/files/11159838/avahi-dbus-monitor_no-start.log): `Start` never called on the service resolvers but `Found` signals still sent.

**Comment by hughsie** [comment]
I see exactly the same -- see bustle image. I've added an artificial 500ms delay before calling Start() to highlight the issue:

![Screenshot from 2023-07-24 10-48-21](https://github.com/lathiat/avahi/assets/151380/7509a6fb-5ca7-40b0-830f-e5d218313609)

@kapetan did you find any workaround?

**Comment by kapetan** [comment]
I ended up using a global signal handler on the DBus client I'm using and switched to the older `Server` interface.

**Comment by hughsie** [comment]
So, the core issue seems to be that in the avahi daemon when we call `avahi_s_service_resolver_prepare()` that actually ends up using `avahi_s_record_browser_new()` for `AVAHI_DNS_TYPE_SRV` and `AVAHI_DNS_TYPE_TXT` -- rather than the `_prepare()` versions. I've made that change locally and it seems to work for me. Patch incoming.
