### ISSUE TITLE
query response being ignored if source port not 5353

### ISSUE THREAD

**Issue by Lovett1991** [lathiat/avahi#448]
Performing a query on a Debian 11 host  (And Ubuntu 22.10) results in a failed response.

```
~$ avahi-resolve --name NCC-74210.local -4
Failed to resolve host name 'NCC-74210.local': Timeout reached
```

For a non failed request the wireshark response looks like this:
```
0000   01 00 5e 00 00 fb 00 1e 06 45 16 36 08 00 45 00
0010   00 47 d5 8d 40 00 ff 11 04 02 c0 a8 00 72 e0 00
0020   00 fb 4e f7 14 e9 00 33 26 e8 00 00 84 00 00 00
0030   00 01 00 00 00 00 09 4e 43 43 2d 37 34 32 31 30
0040   05 6c 6f 63 61 6c 00 00 01 80 01 00 00 00 78 00
0050   04 c0 a8 00 72
```
With
* source port: `20215`
* destination port: `5353`
* expected ipv4 address

Performing this query on another host that does work
Returns 
```
0000   01 00 5e 00 00 fb 00 1e 06 45 13 46 08 00 45 00
0010   00 46 6d 2a 40 00 ff 11 6c 68 c0 a8 00 70 e0 00
0020   00 fb 14 e9 14 e9 00 32 33 55 00 00 84 00 00 00
0030   00 01 00 00 00 00 08 4e 58 2d 37 34 32 30 35 05
0040   6c 6f 63 61 6c 00 00 01 80 01 00 00 00 78 00 04
0050   c0 a8 00 70
```
With
* source port: `5353`
* destination port: `5353`
* expected ipv4 address

When I compared them other than checksums and address differences the only other thing I could see that was different was the source port.

Wierd though because a request that isn't specific to ipv4 does get accepted:
```
~$ avahi-resolve --name NCC-74210.local
NCC-74210.local	fe80::c4d8:31ff:fe17:f9b6
```

wireshark packet:
```
0000   01 00 5e 00 00 fb 00 1e 06 45 16 36 08 00 45 00
0010   00 63 73 ba 40 00 ff 11 65 b9 c0 a8 00 72 e0 00
0020   00 fb 14 28 14 e9 00 4f 87 50 00 00 84 00 00 00
0030   00 02 00 00 00 00 09 4e 43 43 2d 37 34 32 31 30
0040   05 6c 6f 63 61 6c 00 00 1c 80 01 00 00 00 78 00
0050   10 fe 80 00 00 00 00 00 00 c4 d8 31 ff fe 17 f9
0060   b6 c0 0c 00 01 80 01 00 00 00 78 00 04 c0 a8 00
0070   72
```
With
* source port: `5160`
* destination port: `5353`

which contains both the ipv6 and ipv4 addresses.

On a Red hat host without `libnss-mdns` installed I can see that trying to ping this host does resolve the ipv4 address (It seems to send separate ipv4 and ipv6 queries).

Is this a debian problem, or an avahi problem? Is it against spec to have a non `5353` port as the UDP source port?

**Comment by EskoDijk** [comment]
There's plenty of references about source port in the RFC, just search for "source port" or "5353". In short, source ports other than 5353 MUST be supported to be able to answer one-shot queries i.e. "legacy" queries.   There are made by clients that don't implement the fully compliant & continuous mDNS querier role.

I'm guessing the `avahi-resolve` command uses a source port >5353 in case there is no fully compliant mDNS client already running - it does a one-shot query.  If there's a fully compliant mDNS client already running (i.e. avahi-daemon has mDNS started up and is active) then it would probably use this client to do the query - and then source port 5353 MUST be used according to specs.  This may be the difference.

**Comment by evverx** [comment]
> Is it against spec to have a non 5353 port as the UDP source port?

As far as I can see all the packets are responses and according to the RFC they must be silently ignored if the source port isn't 5353:

>    The source UDP port in all Multicast DNS responses MUST be 5353 (the
   well-known port assigned to mDNS).  Multicast DNS implementations
   MUST silently ignore any Multicast DNS responses they receive where
   the source UDP port is not 5353.

I'm not sure why the last packet isn't ignored though. Could it be that `NCC-74210.local.` sent an unsolicited reply from 5353 at some point and it got cached by avahi?

I wonder what runs on `NCC-74210.local.` and why it replies from different ports?

**Comment by Lovett1991** [comment]
The culprit was calico networking on a kubernetes cluster. It was creating iptables-legacy rules, I was able to override the rule temporarily (seconds) and verify before calico would reinsert itself at the top of the chain.

it would appear from your citation that avahi is acting as per the spec.

**Comment by evverx** [comment]
Got it. Thanks! Kubernetes is fun :-)

I think it can be closed then. The last packet is still a mystery but I suspect avahi used a cached unsolicited response with the `AAAA` record `NCC-74210.local.` sent from 5353 before the packet from 5160 arrived.

If there are still replies from ports other than 5353 that avahi doesn't ignore just let me know and I reopen the issue.

**Comment by EskoDijk** [comment]
@evverx Thanks for clarification that the source port of a response MUST be 5353. (For the request, the source port can be other than 5353 in three specific cases listed in section 6.)

**Comment by evverx** [comment]
@EskoDijk agreed. If avahi ignored unicast queries coming from those ports it would be a bug. They seem to be processed fine and even various corner cases like queries with spoofed non-link-local addresses that can lead to traffic apmlification are covered.

**Comment by pemensik** [comment]
It is worth noting multicast source port 5353 is expected only from full mdns implementation. There might be also non-multicast implementation querying local names directly. Specified by https://www.rfc-editor.org/rfc/rfc6762.html#section-5.1. I think some implementations call it legacy mode and some routers use simplified variant. But that covers query source port. Replies should be accepted only from the address the query was sent to. The port has to match listening socket which received it. Not sure if source address should be different in some cases. Multicast DNS implementation does not allow changing source port in avahi configuration, so it should be always 5353.

**Comment by EskoDijk** [comment]
@pemensik Indeed, matching on both address and port before accepting a response is the proper thing to do.

**Comment by evverx** [comment]
> Replies should be accepted only from the address the query was sent to

That's not how mDNS works. Unsolicited responses including announcements and goodbye packets are perfectly fine there.

>    Multicast DNS implementations SHOULD listen for unsolicited responses
   issued by hosts booting up (or waking up from sleep or otherwise
   joining the network).  Since these unsolicited responses may contain
   a useful answer to a question for which the querier is currently
   awaiting an answer, Multicast DNS implementations SHOULD examine all
   received Multicast DNS response messages for useful answers

>   Multicast DNS implementations MAY cache data from any or all
   Multicast DNS response messages they receive, for possible future
   use, provided of course that normal TTL aging is performed on these
   cached resource records.

**Comment by evverx** [comment]
Just to expand on that I agree of course that direct unicast responses shouldn't be accepted willy-nilly
> A Multicast DNS querier MUST only accept unicast responses if
   they answer a recently sent query (e.g., sent within the last two
   seconds) that explicitly requested unicast responses.

but all the packets mentioned in this issue are multicast responses. Direct unicast queries, legacy unicast queries and so on have nothing to do with this issue.

Just in case here's how avahi responds to direct unicast queries
```python
[<Ether  dst=76:1a:af:88:19:10 src=36:30:b6:30:94:d7 type=IPv4 |<IP  version=4 ihl=5 tos=0x0 len=53 id=65454 flags= frag=0 ttl=64 proto=udp chksum=0x5432 src=192.168.82.197 dst=192.168.82.193 |<UDP  sport=36501 dport=mdns len=33 chksum=0x270a |<DNS  id=4022 qr=0 opcode=QUERY aa=0 tc=0 rd=1 ra=0 z=0 ad=1 cd=0 rcode=ok qdcount=1 ancount=0 nscount=0 arcount=0 qd=[<DNSQR  qname=b'H.local.' qtype=A qclass=IN |>] |>>>>,
 <Ether  dst=36:30:b6:30:94:d7 src=76:1a:af:88:19:10 type=IPv4 |<IP  version=4 ihl=5 tos=0x0 len=69 id=6858 flags=DF frag=0 ttl=255 proto=udp chksum=0x3a06 src=192.168.82.193 dst=192.168.82.197 |<UDP  sport=mdns dport=36501 len=49 chksum=0x271a |<DNS  id=4022 qr=1 opcode=QUERY aa=1 tc=0 rd=0 ra=0 z=0 ad=0 cd=0 rcode=ok qdcount=1 ancount=1 nscount=0 arcount=0 qd=[<DNSQR  qname=b'H.local.' qtype=A qclass=IN |>] an=[<DNSRR  rrname=b'H.local.' type=A rclass=IN ttl=10 rdata=192.168.82.193 |>] |>>>>]
```
and legacy queries
```python
[<Ether  dst=01:00:5e:00:00:01 src=36:30:b6:30:94:d7 type=IPv4 |<IP  version=4 ihl=5 tos=0x0 len=53 id=55177 flags= frag=0 ttl=1 proto=udp chksum=0xeebf src=192.168.82.197 dst=224.0.0.1 |<UDP  sport=55113 dport=mdns len=33 chksum=0xf3a1 |<DNS  id=13559 qr=0 opcode=QUERY aa=0 tc=0 rd=1 ra=0 z=0 ad=1 cd=0 rcode=ok qdcount=1 ancount=0 nscount=0 arcount=0 qd=[<DNSQR  qname=b'H.local.' qtype=A qclass=IN |>] |>>>>,
 <Ether  dst=36:30:b6:30:94:d7 src=76:1a:af:88:19:10 type=IPv4 |<IP  version=4 ihl=5 tos=0x0 len=69 id=20515 flags=DF frag=0 ttl=255 proto=udp chksum=0x4ad src=192.168.82.193 dst=192.168.82.197 |<UDP  sport=mdns dport=55113 len=49 chksum=0x271a |<DNS  id=13559 qr=1 opcode=QUERY aa=1 tc=0 rd=0 ra=0 z=0 ad=0 cd=0 rcode=ok qdcount=1 ancount=1 nscount=0 arcount=0 qd=[<DNSQR  qname=b'H.local.' qtype=A qclass=IN |>] an=[<DNSRR  rrname=b'H.local.' type=A rclass=IN ttl=10 rdata=192.168.82.193 |>] |>>>>]
```
There are no issues with source ports there.
