### ISSUE TITLE
avahi is sending the same probe 2 times in wifi connection

### ISSUE THREAD

**Issue by mohamedkallel82** [lathiat/avahi#464]
I am running avahi 0.8 on my device (OpenWRT).
When I connect my device to the network with ethernet and I run the device, I can see my device is sending probe with a name "RYSE-SmartBridge-4B19.local" and my PC (running BCT) is returning Conflict address then I can see my device sending a new probe with a new name "RYSE-SmartBridge-4B19-2.local". And this is a right behavior.

![Screen Shot 2023-06-22 at 5 30 11 PM](https://github.com/lathiat/avahi/assets/54058171/9d4c4e42-5746-4d41-ac57-3b5d6822c4b5)

Now if I connect the same device to the same network but this time in WiFi:
I can see my device is sending probe with a name "RYSE-SmartBridge-4B19.local" and my PC (running BCT) is returning Conflict address then I can see my device sending a new probe with the same previous name "RYSE-SmartBridge-4B19.local" and then after a while it's sending a new probe with a new name "RYSE-SmartBridge-4B19-2.local". And this is not a good behavior according to the apple test tool Bonjour Conformance Test (BCT)

![Screen Shot 2023-06-22 at 5 32 42 PM](https://github.com/lathiat/avahi/assets/54058171/e9ff991a-f4a6-44be-ba66-6624d5e99b65)

what is wrong in avahi with wifi? Can I fix this in the configuration of avahi. seems to be a time issue.
I think in wifi, the avahi did not wait enough before sending the same probe.
if we can't fix this with avahi config. Can I change the time gap in C source code

According to the BCT tool, the time between 2 probes with the same name should be > 237 ms:

![Screen Shot 2023-06-01 at 1 23 42 PM](https://github.com/lathiat/avahi/assets/54058171/69621264-d697-4041-9305-bbed89abc8c1)

**Comment by pemensik** [comment]
Related to PR #309. I didn't know there is a conformance test. Quite bad about it is it requires authorization before downloading and I do not have Apple Developer account to try it myself.

There are obviously issues with the current code and how it processes conflicting name resolution. But I am not yet sure how delay between probes is calculated.

**Comment by pemensik** [comment]
Related to #117 also.

**Comment by mohamedkallel82** [comment]
@pemensik are there a plan to fix this issue in the mainline ?

**Comment by evverx** [comment]
BCT failures are tracked in https://github.com/lathiat/avahi/issues/2. Closing.

(by the way looking at this issue it isn't clear to me whether the BCT requirements (mentioned in the "1.2 Requirements" section of "Bonjour Conformance Test Guideline") were met. Could you add all the details (including the BCT version) to that issue?)
