### ISSUE TITLE
Should entry group change state to "ENTRY_GROUP_COLLISION" if it has conflicting CNAME record?

### ISSUE THREAD

**Issue by azasypkin** [lathiat/avahi#50]
I have the following setup:
1. device-1 fqdn is `device-1.local`;
2. device-2 fqdn is `device-2.local`;
3. On device-1 I add the following CNAME record via `avahi_entry_group_new` and `avahi_entry_group_add_record` - `device-2.local CNAME device-1.local`;
4. Entry group state is changed to `ENTRY_GROUP_ESTABLISHED` and now if I ping `device-2.local` from device-1 I get device-1's address, if I ping it from device-2 I get device-2 addres.

Is that correct behavior? I expected state of entry group to be changed to `ENTRY_GROUP_COLLISION` so that I can choose alternative name.

Thanks!

**Comment by lathiat** [comment]
The collision code does not check for conflicting records of a different RRtype.

This is as per the specification in "Section 9.  Conflict Resolution" of RFC6762 https://tools.ietf.org/html/rfc6762#section-9

> A conflict occurs when a Multicast DNS responder has a unique record
> for which it is currently authoritative, and it receives a Multicast
> DNS response message containing a record with the same name, rrtype
> and rrclass, but inconsistent rdata. 

So, this is a little unexpected but is not a bug
