### ISSUE TITLE
Debug parameter doesn't add to log

### ISSUE THREAD

**Issue by JonMurphy** [lathiat/avahi#502]
I am trying to debug Avahi but I am having trouble getting into the debug mode.  Or any mode that adds avahi log detail.  It seems like this should be simple but I feel like I am doing something stupid!

I enabled debug using this command:
```
/usr/sbin/avahi-daemon --debug -f /etc/avahi/avahi-daemon.conf -D
```

And Is see a few more lines when Avahi is launched but nothing after that - see image:
<img width="1764" alt="avahi vs avahi --debug - Screen Shot 2023-10-27 at 11 18 03 AM" src="https://github.com/lathiat/avahi/assets/15616372/6844f022-0a05-4eab-8cec-81b737cc8a8a">

I feel like I should see log entries similar to this (this is just an example of someone else's posting):
```
avahi-daemon[nnn]: Joining mDNS multicast group on interface eth0.IPv4 with address nnn.nnn.nnn.nnn.
avahi-daemon[nnn]: New relevant interface eth0.IPv4 for mDNS.
avahi-daemon[nnn]: Registering new address record for nnn.nnn.nnn.nnn on eth0.IPv4.
avahi-daemon[nnn]: Leaving mDNS multicast group on interface eth0.IPv6 with address fe80::...:ce61.
```

I let avahi run for more than an hour.  Why are there not more debug log entries for avahi?

Am I missing another setting for log level or verbosity (or severity)??

**How do I get avahi to share more logging details?**

**Comment by evverx** [comment]
> Am I missing another setting for log level or verbosity (or severity)??

There are no other settings unfortunately. avahi doesn't log much even with the debug option enabled:
```sh
git grep avahi_log_debug | grep -v test
```
if none of those events are triggered avahi stays silent.

**Comment by evverx** [comment]
Either way I think it can be closed. If there are places where you think avahi should log more feel free to open a PR. Thanks!

**Comment by JonMurphy** [comment]
My bug is that it is not logging at all!

Why am I not seeing thing like:
```
Joining mDNS multicast group on interface
New relevant interface eth0
Registering new address record for 
Leaving mDNS multicast group on I
```

**Comment by evverx** [comment]
> Why am I not seeing things like??

Looking at the screenshot as far as I can see they are on the right and on the left. What makes you think that they should appear again?

**Comment by JonMurphy** [comment]
Should they not appear for each client that connects?

**Comment by evverx** [comment]
No they shouldn't. They appear when new network interfaces relevant to avahi pop up

**Comment by JonMurphy** [comment]
I am hoping (was hoping) to use it to help debug a name conflict issue (similar to the ones posted in the issue area).

**Comment by evverx** [comment]
If there are conflicts avahi shows something like
```
Received conflicting record [C.local    IN      AAAA fe80::3430:b6ff:fe30:94d7 ; ttl=120] with local record to be. Withdrawing.
...
Host name conflict, retrying with C-2
```
if it doesn't show anything like that it probably means that there are no conflicts.

> Is there another way to debug?

I think it should be possible to collect packets receievied/sent by avahi to see whether there are any packets that indicate any conflicts.

**Comment by JonMurphy** [comment]
I did that also! But I was not able to find the issue...

```
tcpdump -i blue0 host 192.168.65.212 and port 5353 -w blue5353.pcap &
tcpdump -i green0 host 192.168.60.212 and port 5353 -w green5353.pcap
```

This may be too big of a tangent (and I can open a separate thread if needed):
Was a fix found for name conflicts?  I found lots of suggestions and I see lots or PR submitted...

**Comment by evverx** [comment]
> Was a fix found for name conflicts?

There is nothing inherently wrong with conflicts. They are part of mDNS: https://datatracker.ietf.org/doc/html/rfc6762#section-9.

> Was a fix found for name conflicts?

I think one bug where the reflector reflected probes back was fixed. The other issue is open and the PR attempting to fix it introduced a regression so it hasn't been merged.

**Comment by JonMurphy** [comment]
> There is nothing inherently wrong with conflicts.
For me there is when the name of the device changes every reboot and I need to go looking for it.

> I think one bug where the reflector reflected probes back was fixed.
My issue is reflector based.  I enabled it recently and had lots of name conflicts.  Can you point me to the Issue number?
(I did see the regression thread on the PR)

**Comment by evverx** [comment]
> Can you point me to the Issue number?

https://github.com/lathiat/avahi/pull/263

**Comment by JonMurphy** [comment]
Thanks!  I had not seen that issue before.  I'll keep looking!  Thank you for your help!  It is appreciated!

Just so you know, Avahi is an add-on for the [IPFire](https://www.ipfire.org/features) distro.

Thank you again!
Jon
