### ISSUE TITLE
Change hostname directly using system command possible with this version or not ?

### ISSUE THREAD

**Issue by navyasingh6-7** [lathiat/avahi#505]
avahi-set-host-name command -Can I use this command to set hostname of my device dynamically ? does this version supports this system command?

**Comment by evverx** [comment]
It can be used to dynamically set the name advertised by avahi. It doesn't change the system hostname.

**Comment by navyasingh6-7** [comment]
Okay thanks. When I run this command using system call in my application running linux in it, it gives command not found, regardless of using sudo or not. What could be the issue an dhow to resolve it ? Are there any other commands availabel to dynamically set the name advertised by avahi or how i can use this  avahi-set-host-name command to do that ? 

> It can be used to dynamically set the name advertised by avahi. It doesn't change the system hostname.

**Comment by evverx** [comment]
> it gives command not found

Looks like it isn't installed. I'm not sure how avahi is built/packaged/installed in this particular case but distributions usually include that command in a separate package named `avahi-tools` or something like that. If it's installed it could be that the `PATH` environment variable isn't set so `system` can't find it.

> Are there any other commands availabel to dynamically set the name advertised by avahi

It should be possible to call the `SetHostName` D-Bus method using any D-Bus client (and that's what `avahi-set-host-name` does under the hood). If `busctl` is available It would look like
```
busctl call org.freedesktop.Avahi / org.freedesktop.Avahi.Server SetHostName "s" new-name
```

**Comment by navyasingh6-7** [comment]
Okay, Thanks. 
I have avahi installed but its older version 0.6.2 something. Can that cause issue? I thought so, so I installed a new avahi release 0.8 and tried configuring it. Facing some issue. It has avahi-set-host-name.c file and in avahi-utils some makefiles. I tried make or suod make etc, it all gives command not found. 
I also tried checking busctl , it showed same-not found. Although I could see dbus folder. 
Also, there is busybox currently in my gateway device application. 
With all this information can you suggest some way how to procced or what to look for ? 

> > it gives command not found
> 
> Looks like it isn't installed. I'm not sure how avahi is built/packaged/installed in this particular case but distributions usually include that command in a separate package named `avahi-tools` or something like that. If it's installed it could be that the `PATH` environment variable isn't set so `system` can't find it.
> 
> > Are there any other commands availabel to dynamically set the name advertised by avahi
> 
> It should be possible to call the `SetHostName` D-Bus method using any D-Bus client (and that's what `avahi-set-host-name` does under the hood). If `busctl` is available It would look like
> 
> ```
> busctl call org.freedesktop.Avahi / org.freedesktop.Avahi.Server SetHostName "s" new-name
> ```

**Comment by evverx** [comment]
I'm sorry but it isn't a support forum. Please try asking those questions on mailing lists where those routers/gateways are usually discussed. It should probably be possible to find out how to build and install avahi there.

If all else fails and if the device isn't fully read-only it should be possible to use the "host-name" setting https://github.com/lathiat/avahi/blob/287494b526dc84a90349cf44fe1686f664dc4cc5/man/avahi-daemon.conf.5.xml.in#L36-L40

**Comment by navyasingh6-7** [comment]
> I'm sorry but it isn't a support forum. Please try asking those questions on mailing lists where those routers/gateways are usually discussed. It should probably be possible to find out how to build and install avahi there.
> 
> If all else fails and if the device isn't fully read-only it should be possible to use the "host-name" setting
> 
> https://github.com/lathiat/avahi/blob/287494b526dc84a90349cf44fe1686f664dc4cc5/man/avahi-daemon.conf.5.xml.in#L36-L40

Okay. Thanks.
