### ISSUE TITLE
getpwnam failed. errno is 2

### ISSUE THREAD

**Issue by blackStar1314** [lathiat/avahi#510]
I cross compile avahi-daemon. But, failed when running on host. 
Error message: Failed to find user 'root'.

Details following:
./configure \
-build=x86_64-linux-gnu \
--host=arm-linux-gnueabihf \
--with-distro=none \
--sysconfdir=/etc \
--with-xml=expat \
--with-avahi-user="root" \
--with-avahi-group="root" \
--localstatedir=/var \
--disable-gdbm \
--disable-autoipd \
--disable-qt3 \
--disable-qt4 \
--disable-gtk \
--disable-gtk3 \
--disable-python \
--disable-mono \
--disable-monodoc \
--disable-xmltoman \
--disable-manpages \
--disable-glib \
--disable-gobject \
--disable-stack-protector \
CC=arm-linux-gnueabihf-gcc 

I found that it call `getpwnam` api failed. But, I don't know why.

**Comment by evverx** [comment]
Looks like `/etc/passwd` doesn't exist or something like that. Could you run avahi under strace and attach its output to see what exactly fails there?

Either way I don't think it has anything with avahi itself. Looks the system isn't fully set up.

**Comment by blackStar1314** [comment]
`/etc/passwd` :
![image](https://github.com/lathiat/avahi/assets/53989046/fbf4af91-2539-48e3-afc2-ee160f1d59b2)

I thinks that the system the system isn't fully set up . 
I try to that.
Thanks!
