### ISSUE TITLE
Port not being released by avahi inside docker

### ISSUE THREAD

**Issue by almichala** [lathiat/avahi#524]
As a developer I am  using avahi inside a docker container (to resolve an IP). When I stop my container (either Ctrl+C or docker compose stop) avahi still retains the port used by the daemon for about 60 seconds. I would like to have the port released immediately when the avahi daemon is killed by the container.

**Comment by evverx** [comment]
I don't think it has anything to do with avahi. Looks like whatever manages processes inside containers fails to stop things properly.

> When I stop my container (either Ctrl+C or docker compose stop) avahi still retains the port used by the daemon for about 60 seconds

Could you attach any logs showing where avahi is supposedly killed but keeps using the port?

**Comment by evverx** [comment]
Either way I don't think it's an avahi issue. Closing.

If you can attach any logs showing that it's an avahi issue (for example it ignores signals it shouldn't ignore or something like that) I can always reopen it.
