### ISSUE TITLE
avahi-autoipd: dhclient hooks should check if avahi-autoipd is present before trying to run it

### ISSUE THREAD

**Issue by mbiebl** [lathiat/avahi#60]
In Debian, uninstalling a package does not remove conffiles. Those are only removed when explicitly requested via "--purge". Conffiles are typically files shipped in /etc. In case of avahi, this means the /etc/dhclient hooks can be installed but the actual binary is missing. The following bug was filed as a result. 

Dear Maintainer,

If one removes (but does not purge) avahi-autoipd, one is likely to
start seeing this sort of thing in the system logs:

  root: /etc/dhcp/dhclient-exit-hooks.d/zzz_avahi-autoipd returned non-zero exit status 127

=-=-=-=-=-=-=-=-
  For those finding this as a result of a search for the above error message:

  The problem is that the config files are left in place when one removes
  a package, including these problematic scripts.  To remove them one needs
  to purge the package, thus:

```
 sudo apt-get purge avahi-autoipd
```

=-=-=-=-=-=-=-=-

The bug in the package could be fixed by changing the scripts to use
this line instead (BTW the reason for inverting the test is that that
ensures that the script's return value is 0 if the file is missing):

  [ ! -x /usr/sbin/avahi-autoipd ] || /usr/sbin/avahi-autoipd -wD $interface 2> /dev/null

I can carry this as a downstream patch, but if you see value in having this fixed upstream, feel free to apply the patch at

http://anonscm.debian.org/cgit/pkg-utopia/avahi.git/tree/debian/patches/0001-avahi-autoipd-fix-dhclient-hooks-to-check-for-avahi-.patch

Thanks for considering

**Comment by lathiat** [comment]
Thanks for sending this through, I've applied it as supplied!

**Comment by popina1994** [comment]
I am having the similar issue, avahi-autopid always fails and because of that it renews my IP every 2 minutes. 
I explained the problem here:
https://stackoverflow.com/questions/49824545/dhcp-client-tries-renewal-of-ip-address-every-2-minutes
Any idea what can it be?
