### ISSUE TITLE
Avahi-client does not get a notification from Avahi-daemon for Registering new address record 

### ISSUE THREAD

**Issue by jitendrajagasia** [lathiat/avahi#68]
Hello All,

I am currently facing an issue with Avahi-daemon & Avahi-client

The issue is I do not see Avahi-client like avahi-browse getting update from Avahi-daemon for the change in Registering new address record. It show the old Withdrawing address record in the avahi-browse & it never gets updated. If I restart the avahi-browse then I see the new registered address record.

In my case the old Withdrawing address is the IPv6 link local address & the Registering new address is the IPv6 global address assigned to that interface by Radvd.
It is easy to reproduce this issue. 
# Please let me know if anyone else has also faced the same issue. Or is there any know solution for this issue.

 avahi-daemon[325]: Registering new address record for fa10:53ba:e9a0:de12:58a1:d8ff:fedd:8b1a on eth0*.
#  avahi-daemon[325]: Withdrawing address record for fe80::58a1:d8ff:fedd:8b1a on eth0.

Thanks

**Comment by lathiat** [comment]
I think this is the same issue as #95.  Closing this as duplicate since it has more information.
If you disagree please let me know!

Hopefully we can get that fixed up
