### ISSUE TITLE
Stuck registering

### ISSUE THREAD

**Issue by lathiat** [lathiat/avahi#7]
From:
http://stackoverflow.com/questions/25439158/avahi-daemon-gets-stuck-registering-a-service-im-publishing-with-avahi-publish/30757900#30757900

I've noticed that ticket 201 has been around for some while on the Avahi site. Though I couldn't even register there... Looks like development on this project has fallen off. We experienced a similar problem. The below addressed it (for us):

```
diff --git a/avahi-core/server.c b/avahi-core/server.c
index 69a1d02..03d4fc1 100644
--- a/avahi-core/server.c
+++ b/avahi-core/server.c
@@ -1216,8 +1216,8 @@ static void register_browse_domain(AvahiServer *s) {
 static void register_stuff(AvahiServer *s) {
     assert(s);

-    server_set_state(s, AVAHI_SERVER_REGISTERING);
     s->n_host_rr_pending ++; /** Make sure that the state isn't changed tp AVAHI_SERVER_RUNNING too early */
+    server_set_state(s, AVAHI_SERVER_REGISTERING);

     register_hinfo(s);
     register_browse_domain(s);
```

**Comment by cmcqueen** [comment]
I have had this issue on a BeagleBone Black based system built with Yocto, after upgrading from kernel 3.14.x to 4.4.x. I don't know why I only came across this issue after the kernel upgrade.

The above patch from tmds seems to fix the issue.

**Comment by evverx** [comment]
I think https://github.com/lathiat/avahi/commit/cb15988c4c676410549ef1d04487107cd484b353 was supposed to address this issue.
