### ISSUE TITLE
libtool.m4: error: problem compiling CXX test program

### ISSUE THREAD

**Issue by chinna6226** [lathiat/avahi#75]
Getting error while ./configure avahi-daemon project. Please verify this one or please correct me

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking whether make supports nested variables... (cached) yes
checking for stow... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking whether we are using the GNU C++ compiler... no
checking whether /usr/bin/arm-linux-gnueabi-gcc accepts -g... no
checking dependency style of /usr/bin/arm-linux-gnueabi-gcc... gcc3
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define **EXTENSIONS**... yes
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking whether gcc -std=gnu99 needs -traditional... no
checking whether libssp exists... no
checking whether stack-smashing protection is available... yes
checking whether stack-smashing protection is buggy... no
checking whether gcc -std=gnu99 accepts -fstack-protector... yes
checking whether /usr/bin/arm-linux-gnueabi-gcc accepts -fstack-protector... no
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc -std=gnu99... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc -std=gnu99 object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if gcc -std=gnu99 static flag -static works... yes
checking if gcc -std=gnu99 supports -c -o file.o... yes
checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the gcc -std=gnu99 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... /lib/cpp
checking whether the /usr/bin/arm-linux-gnueabi-gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
**libtool.m4: error: problem compiling CXX test program**
checking for /usr/bin/arm-linux-gnueabi-gcc option to produce PIC...  -DPIC
checking if /usr/bin/arm-linux-gnueabi-gcc PIC flag  -DPIC works... no
checking if /usr/bin/arm-linux-gnueabi-gcc static flag  works... no
checking if /usr/bin/arm-linux-gnueabi-gcc supports -c -o file.o... no
checking if /usr/bin/arm-linux-gnueabi-gcc supports -c -o file.o... (cached) no
checking whether the /usr/bin/arm-linux-gnueabi-gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... unsupported
checking whether the C++ compiler works... no
configure: error: in `/home/jagan/Mywork/avahi-0.6.32':
configure: error: The C++ compiler does not work
See`config.log' for more details

**Comment by lathiat** [comment]
Most likely you are not using the correct flags to actually cross compile.. you need to use something like this:
./configure --host=arm-linux-gnueabi (I suspect you tried to set CC directly?)

Basically for --host to work, /usr/bin/$HOST-$CC has to exist, as well as $HOST-$CXX and others.  For ubuntu I installed gcc-arm-linux-gnueabi, g++-arm-linux-gnueabi, binutils-arm-linux-gnueabi

I also had to use --disable-gobject that seems broken for some reason.

You'll then need to have the build-dependant libraries for that architecture installed, e.g. libxml2, etc.


Let me know if that helps.
