### ISSUE TITLE
No package 'qt-mt' found

### ISSUE THREAD

**Issue by chinna6226** [lathiat/avahi#76]
Hi please resolve this error. I installed qt4 package from command terminal. 

checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... yes
checking for dgettext in libc... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... (cached) /usr/bin/msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... (cached) /usr/bin/msgfmt
checking for xgettext... (cached) /usr/bin/xgettext
checking for pkg-config... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GLIB20... yes
checking for GOBJECT... yes
checking for gobject-introspection... no
checking for QT3... no
configure: error: Package requirements ( qt-mt >= 3.0.0 ) were not met:

**No package 'qt-mt' found**

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables QT3_CFLAGS
and QT3_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by lathiat** [comment]
Comment above is the correct answer.  Avahi intentionally doesn't 'auto-disable' anything it can't find to ensure it's obvious what is and isn't being built.  You need to specifically disable it.
