### ISSUE TITLE
Allow for binary TXT record values in XML

### ISSUE THREAD

**Issue by edmont** [lathiat/avahi#77]
According to https://tools.ietf.org/html/rfc6763#section-6.5 :

> The value is opaque binary data.  Often the value for a particular attribute will be US-ASCII [RFC20] or UTF-8 [RFC3629] text, but it is legal for a value to be any binary data.

However, the current static XML service definition only allows printable characters to be included as TXT record value (http://linux.die.net/man/5/avahi.service).

From an old @poettering message to the list (https://lists.freedesktop.org/archives/avahi/2010-August/001915.html):

> The C API allows you to create binary TXT fields very easily. However, this is not supported in the XML definition for static services, simply because there is no nice way to include binary data in XML files.

What about an attribute in the XML 'text-record' tag?
`<txt-record value="binary">"val=0xf0a9"</txt-record>
`

**Comment by edmont** [comment]
Another option: https://github.com/lathiat/avahi/pull/116

**Comment by lathiat** [comment]
Planning to merge #116, so closing this out.  Thanks.
