### ISSUE TITLE
Building Avahi for Android?

### ISSUE THREAD

**Issue by paulobrizolara** [lathiat/avahi#82]
Is possible to build/use Avahi in Android?
If yes, how? 
Are there any known difference from the "normal build" besides the use of  ndk/cross-compiling?

I am thinking in use dns-sd in Android from c++ code, but don't know if there is some kind of library that allows this.

Thanks!

**Comment by lathiat** [comment]
Someone appears to have blogged about this here:
http://gaiger-programming.blogspot.co.at/2015/12/utilize-avahi-libraries-in-android-for.html

Happy to accept properly formatted PRs to support building on Android, but won't spend any devtime on it directly.
