### ISSUE TITLE
Avahi not able to find services on local machine without network

### ISSUE THREAD

**Issue by zevv** [lathiat/avahi#88]
Sorry for the noise, I've also asked this question on the avahi-list on freedesktop, but this list seems to be kind of dead.

I'm working on a platform consisting of a number of services which rely
on mDNS for mutual discovery to provide load balancing and failover -
all works fine with Avahi, no problems here.

I'm now trying to configure a system running with a number of services
on a single host with limited network connectivity. Most important is
that the machine is not allowed to use mDNS on the physical network
interface for administrative reasons.

My assumption was that this would be no problem and that things would
probably work just fine when restricting avahi-daemon to run on the lo
interface, an empty bridge or a dummy network interface. I've now spent
a few hours trying to get this to work, but to no avail.

Here are the steps I expected to work:

- Create a dummy network interface
````
  # modprobe dummy
  # ifconfig dummy0 172.16.0.0/24 multicast up
````
- Configure avahi-daemon to restrict itself to the dummy interface
````
  allow-interfaces=dummy0
````
- Start avahi daemon and discover services on the same machine:
````
  avahi-browse -a
````
Result: no results whatsoever.

The funny thing is that running wireshark on dummy0 shows actual mDNS
traffic happening: I see the initial announcments when avahi-daemon
starts and I see the requests on the network when running avahi-browse.
Still, no results are returned when browsing.

Can anobody point out my error?

**Comment by dschmidt** [comment]
Why did you close this? What was your conclusion/solution?
