### ISSUE TITLE
Message on bottom of avahi browser window intended to be in italics is not

### ISSUE THREAD

**Issue by Wesalius** [lathiat/avahi#91]
The bottom message at the window of avahi browser shows the bottom text is not in italics, but the tags for italics are shown instead.
![avahi](https://cloud.githubusercontent.com/assets/5477342/20650030/430fd090-b4cd-11e6-8eed-500a19776ee7.png)

**Comment by lathiat** [comment]
Thanks for the report, PR from Piotr Drąg to fix this was merged.  Thanks to both of you!
